/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package hethongnhathuocduocankhang.gui.baocao;

import hethongnhathuocduocankhang.dao.HoaDonDAO;
import hethongnhathuocduocankhang.dao.PhieuTraHangDAO;
import hethongnhathuocduocankhang.entity.HoaDon;
import hethongnhathuocduocankhang.entity.PhieuTraHang;
import java.awt.*;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyChangeListener;
import java.text.DecimalFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JProgressBar;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.SwingWorker;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import com.toedter.calendar.JDateChooser;

/**
 *
 * @author MINH KHANG
 */
public class BaoCaoDoanhThu extends javax.swing.JPanel {

    private JDateChooser datePickerTuNgay;
    private JDateChooser datePickerDenNgay;
    private JComboBox<Integer> cmbTuThang;
    private JComboBox<Integer> cmbDenThang;
    private JComboBox<Integer> cmbTuQuy;
    private JComboBox<Integer> cmbDenQuy;
    private JComboBox<Integer> cmbTuNam;
    private JComboBox<Integer> cmbDenNam;
    private JComboBox<String> cmbLoaiThongKe;
    private JButton btnXemBaoCao;
    private JButton btnXuatFile;
    private JTable table;
    private DefaultTableModel model;
    private JLabel lblTongDoanhThu;

    /**
     * Creates new form BaoCaoDoanhThu
     */
    public BaoCaoDoanhThu() {
        initComponents();
        setupUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel2.add(jScrollPane2);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void setupUI() {
        this.setLayout(new BorderLayout(10, 10));
        this.setBorder(new EmptyBorder(10, 10, 10, 10));

        // Panel NORTH (Bộ lọc báo cáo)
        JPanel pnlNorth = new JPanel();
        pnlNorth.setLayout(new BorderLayout());

        JPanel pnlFilter = new JPanel(new FlowLayout(FlowLayout.LEFT, 15, 5));
        pnlFilter.setBorder(new EmptyBorder(0, 0, 10, 0));
        Font fontLabel = new Font("Arial", Font.BOLD, 14);
        Font fontInput = new Font("Arial", Font.PLAIN, 14);

        JLabel lblTuNgay = new JLabel("Từ ngày:");
        lblTuNgay.setFont(fontLabel);
        datePickerTuNgay = new JDateChooser();
        datePickerTuNgay.setFont(fontInput);
        datePickerTuNgay.setDate(java.util.Date.from(LocalDate.now().minusMonths(1).atStartOfDay(java.time.ZoneId.systemDefault()).toInstant())); // Mặc định 1 tháng trước

        // Ngăn chọn ngày lớn hơn ngày hiện tại
        PropertyChangeListener dateListenerTuNgay = evt -> {
            if ("date".equals(evt.getPropertyName())) {
                java.util.Date selectedDate = (java.util.Date) evt.getNewValue();
                if (selectedDate != null) {
                    LocalDate selectedLocalDate = LocalDate.ofInstant(selectedDate.toInstant(), java.time.ZoneId.systemDefault());
                    if (selectedLocalDate.isAfter(LocalDate.now())) {
                        datePickerTuNgay.setDate(java.util.Date.from(LocalDate.now().atStartOfDay(java.time.ZoneId.systemDefault()).toInstant()));
                    }
                }
            }
        };
        datePickerTuNgay.addPropertyChangeListener(dateListenerTuNgay);

        JLabel lblDenNgay = new JLabel("Đến ngày:");
        lblDenNgay.setFont(fontLabel);
        datePickerDenNgay = new JDateChooser();
        datePickerDenNgay.setFont(fontInput);
        datePickerDenNgay.setDate(java.util.Date.from(LocalDate.now().atStartOfDay(java.time.ZoneId.systemDefault()).toInstant())); // Mặc định hôm nay

        // Ngăn chọn ngày lớn hơn ngày hiện tại
        PropertyChangeListener dateListenerDenNgay = evt -> {
            if ("date".equals(evt.getPropertyName())) {
                java.util.Date selectedDate = (java.util.Date) evt.getNewValue();
                if (selectedDate != null) {
                    LocalDate selectedLocalDate = LocalDate.ofInstant(selectedDate.toInstant(), java.time.ZoneId.systemDefault());
                    if (selectedLocalDate.isAfter(LocalDate.now())) {
                        datePickerDenNgay.setDate(java.util.Date.from(LocalDate.now().atStartOfDay(java.time.ZoneId.systemDefault()).toInstant()));
                    }
                }
            }
        };
        datePickerDenNgay.addPropertyChangeListener(dateListenerDenNgay);

        JLabel lblLoai = new JLabel("Loại thống kê:");
        lblLoai.setFont(fontLabel);
        String[] arrLoai = {"Theo ngày", "Theo tháng", "Theo quý", "Theo năm"};
        cmbLoaiThongKe = new JComboBox<>(arrLoai);
        cmbLoaiThongKe.setFont(fontInput);
        cmbLoaiThongKe.setPreferredSize(new Dimension(120, 30));
        cmbLoaiThongKe.addActionListener(e -> {
            String loai = (String) cmbLoaiThongKe.getSelectedItem();
            boolean isTheoNgay = "Theo ngày".equals(loai);
            boolean isTheoThang = "Theo tháng".equals(loai);
            boolean isTheoQuy = "Theo quý".equals(loai);
            boolean isTheoNam = "Theo năm".equals(loai);

            lblTuNgay.setVisible(isTheoNgay);
            datePickerTuNgay.setVisible(isTheoNgay);
            lblDenNgay.setVisible(isTheoNgay);
            datePickerDenNgay.setVisible(isTheoNgay);

            cmbTuThang.setVisible(isTheoThang);
            cmbDenThang.setVisible(isTheoThang);

            cmbTuQuy.setVisible(isTheoQuy);
            cmbDenQuy.setVisible(isTheoQuy);

            cmbTuNam.setVisible(isTheoNam);
            cmbDenNam.setVisible(isTheoNam);

            pnlFilter.revalidate();
            pnlFilter.repaint();
        });

        // Mặc định chọn "Theo ngày" và hiện JDatePicker
        // cmbLoaiThongKe.setSelectedItem("Theo ngày");
        // lblTuNgay.setVisible(true);
        // datePickerTuNgay.setVisible(true);
        // lblDenNgay.setVisible(true);
        // datePickerDenNgay.setVisible(true);

        // Tạo combo tháng
        cmbTuThang = new JComboBox<>();
        for (int i = 1; i <= 12; i++) cmbTuThang.addItem(i);
        cmbTuThang.setFont(fontInput);
        cmbTuThang.setPreferredSize(new Dimension(80, 30));

        cmbDenThang = new JComboBox<>();
        for (int i = 1; i <= 12; i++) cmbDenThang.addItem(i);
        cmbDenThang.setFont(fontInput);
        cmbDenThang.setPreferredSize(new Dimension(80, 30));

        // Tạo combo quý
        cmbTuQuy = new JComboBox<>();
        for (int i = 1; i <= 4; i++) cmbTuQuy.addItem(i);
        cmbTuQuy.setFont(fontInput);
        cmbTuQuy.setPreferredSize(new Dimension(80, 30));

        cmbDenQuy = new JComboBox<>();
        for (int i = 1; i <= 4; i++) cmbDenQuy.addItem(i);
        cmbDenQuy.setFont(fontInput);
        cmbDenQuy.setPreferredSize(new Dimension(80, 30));

        int minYear = 2025;
        int maxYear = LocalDate.now().getYear();
        cmbTuNam = new JComboBox<>();
        for (int i = minYear; i <= maxYear; i++) cmbTuNam.addItem(i);
        cmbTuNam.setFont(fontInput);
        cmbTuNam.setPreferredSize(new Dimension(80, 30));

        cmbDenNam = new JComboBox<>();
        for (int i = minYear; i <= maxYear; i++) cmbDenNam.addItem(i);
        cmbDenNam.setFont(fontInput);
        cmbDenNam.setPreferredSize(new Dimension(80, 30));

        // Ẩn tất cả ban đầu
        datePickerTuNgay.setVisible(false);
        datePickerDenNgay.setVisible(false);
        cmbTuThang.setVisible(false);
        cmbDenThang.setVisible(false);
        cmbTuQuy.setVisible(false);
        cmbDenQuy.setVisible(false);
        cmbTuNam.setVisible(false);
        cmbDenNam.setVisible(false);

        btnXemBaoCao = new JButton("Xem báo cáo");
        btnXemBaoCao.setFont(fontLabel);
        btnXemBaoCao.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                xemBaoCao();
            }
        });

        btnXuatFile = new JButton("Xuất file báo cáo");
        btnXuatFile.setFont(fontLabel);
        btnXuatFile.addActionListener(e -> xuatBaoCaoExcel());

        pnlFilter.add(lblTuNgay);
        pnlFilter.add(datePickerTuNgay);
        pnlFilter.add(lblDenNgay);
        pnlFilter.add(datePickerDenNgay);
        pnlFilter.add(cmbTuThang);
        pnlFilter.add(cmbDenThang);
        pnlFilter.add(cmbTuQuy);
        pnlFilter.add(cmbDenQuy);
        pnlFilter.add(cmbTuNam);
        pnlFilter.add(cmbDenNam);
        pnlFilter.add(lblLoai);
        pnlFilter.add(cmbLoaiThongKe);
        pnlFilter.add(btnXemBaoCao);
        pnlFilter.add(btnXuatFile);

        pnlNorth.add(pnlFilter, BorderLayout.CENTER);

        // Panel CENTER (Table)
        JPanel pnlCenter = new JPanel(new BorderLayout());
        String[] columnNames = {"Thời gian", "Tổng hóa đơn", "Tổng phiếu trả", "Doanh thu"};
        model = new DefaultTableModel(columnNames, 0);
        table = new JTable(model);
        table.setFont(new Font("Arial", Font.PLAIN, 14));
        table.getTableHeader().setFont(new Font("Arial", Font.BOLD, 14));
        JScrollPane scrollPane = new JScrollPane(table);
        pnlCenter.add(scrollPane, BorderLayout.CENTER);

        // Panel SOUTH (Tổng doanh thu)
        JPanel pnlSouth = new JPanel(new FlowLayout(FlowLayout.RIGHT));
        lblTongDoanhThu = new JLabel("Tổng doanh thu: 0 VND");
        lblTongDoanhThu.setFont(new Font("Arial", Font.BOLD, 16));
        pnlSouth.add(lblTongDoanhThu);

        // Thêm vào main panel
        this.add(pnlNorth, BorderLayout.NORTH);
        this.add(pnlCenter, BorderLayout.CENTER);
        this.add(pnlSouth, BorderLayout.SOUTH);

        // Xóa các component cũ nếu có
        this.remove(jPanel1);
        this.remove(jPanel2);

        // Mặc định chọn "Theo ngày" và hiện JDatePicker
        cmbLoaiThongKe.setSelectedItem("Theo ngày");
        lblTuNgay.setVisible(true);
        datePickerTuNgay.setVisible(true);
        lblDenNgay.setVisible(true);
        datePickerDenNgay.setVisible(true);
    }

    private void xemBaoCao() {
        // Tạo dialog loading
        JDialog loadingDialog = new JDialog((java.awt.Frame) SwingUtilities.getWindowAncestor(this), "Đang tải dữ liệu", true);
        loadingDialog.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        loadingDialog.setSize(300, 100);
        loadingDialog.setLocationRelativeTo(this);

        JPanel panel = new JPanel(new BorderLayout());
        panel.add(new JLabel("Đang tải dữ liệu báo cáo, vui lòng chờ...", JLabel.CENTER), BorderLayout.CENTER);
        JProgressBar progressBar = new JProgressBar();
        progressBar.setIndeterminate(true);
        panel.add(progressBar, BorderLayout.SOUTH);
        loadingDialog.add(panel);

        SwingWorker<Void, Void> worker = new SwingWorker<Void, Void>() {
            private List<String> allKeysResult;
            private double tongDoanhThuResult;

            @Override
            protected Void doInBackground() throws Exception {
                String loaiThongKe = (String) cmbLoaiThongKe.getSelectedItem();

                // Query DB
                HoaDonDAO hoaDonDAO = new HoaDonDAO();
                PhieuTraHangDAO phieuTraDAO = new PhieuTraHangDAO();

                ArrayList<HoaDon> hoaDons = hoaDonDAO.getAllHoaDon();
                ArrayList<PhieuTraHang> phieuTras = phieuTraDAO.getAllPhieuTraHang();

                // Tạo list tất cả khoảng thời gian trong range
                List<String> allKeys = new ArrayList<>();
                if ("Theo ngày".equals(loaiThongKe)) {
                    Date tuNgay = datePickerTuNgay.getDate();
                    Date denNgay = datePickerDenNgay.getDate();
                    LocalDate startDate = tuNgay.toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();
                    LocalDate endDate = denNgay.toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();
                    for (LocalDate date = startDate; !date.isAfter(endDate); date = date.plusDays(1)) {
                        allKeys.add(date.format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));
                    }
                } else if ("Theo tháng".equals(loaiThongKe)) {
                    int tuThang = (Integer) cmbTuThang.getSelectedItem();
                    int tuNam = (Integer) cmbTuNam.getSelectedItem();
                    int denThang = (Integer) cmbDenThang.getSelectedItem();
                    int denNam = (Integer) cmbDenNam.getSelectedItem();
                    for (int nam = tuNam; nam <= denNam; nam++) {
                        int startThang = (nam == tuNam) ? tuThang : 1;
                        int endThang = (nam == denNam) ? denThang : 12;
                        for (int thang = startThang; thang <= endThang; thang++) {
                            allKeys.add(String.format("%02d/%d", thang, nam));
                        }
                    }
                } else if ("Theo quý".equals(loaiThongKe)) {
                    int tuQuy = (Integer) cmbTuQuy.getSelectedItem();
                    int tuNam = (Integer) cmbTuNam.getSelectedItem();
                    int denQuy = (Integer) cmbDenQuy.getSelectedItem();
                    int denNam = (Integer) cmbDenNam.getSelectedItem();
                    for (int nam = tuNam; nam <= denNam; nam++) {
                        int startQuy = (nam == tuNam) ? tuQuy : 1;
                        int endQuy = (nam == denNam) ? denQuy : 4;
                        for (int quy = startQuy; quy <= endQuy; quy++) {
                            allKeys.add("Quý " + quy + " năm " + nam);
                        }
                    }
                } else if ("Theo năm".equals(loaiThongKe)) {
                    int tuNam = (Integer) cmbTuNam.getSelectedItem();
                    int denNam = (Integer) cmbDenNam.getSelectedItem();
                    for (int nam = tuNam; nam <= denNam; nam++) {
                        allKeys.add("Năm " + nam);
                    }
                }

                allKeysResult = allKeys;
                tongDoanhThuResult = 0;

                // Tính doanh thu
                model.setRowCount(0);
                for (String key : allKeys) {
                    double tongHD = hoaDons.stream()
                        .filter(hd -> getKey(hd, loaiThongKe).equals(key))
                        .mapToDouble(HoaDon::getTongTien)
                        .sum();
                    double tongPT = phieuTras.stream()
                        .filter(pt -> getKey(pt, loaiThongKe).equals(key))
                        .mapToDouble(PhieuTraHang::getTongTienHoanTra)
                        .sum();
                    double doanhThu = tongHD - tongPT;
                    model.addRow(new Object[]{key, dinhDangTien(tongHD), dinhDangTien(tongPT), dinhDangTien(doanhThu)});
                    tongDoanhThuResult += doanhThu;
                }

                return null;
            }

            @Override
            protected void done() {
                loadingDialog.dispose();
                lblTongDoanhThu.setText("Tổng doanh thu: " + dinhDangTien(tongDoanhThuResult));
            }
        };

        worker.execute();
        loadingDialog.setVisible(true);
    }

    private void xuatBaoCaoExcel() {
        if (model.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Không có dữ liệu để xuất!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setSelectedFile(new java.io.File("BaoCaoDoanhThu.xlsx"));
        if (fileChooser.showSaveDialog(this) != JFileChooser.APPROVE_OPTION) {
            return;
        }

        java.io.File file = fileChooser.getSelectedFile();
        if (!file.getName().endsWith(".xlsx")) {
            file = new java.io.File(file.getAbsolutePath() + ".xlsx");
        }

        try (Workbook workbook = new XSSFWorkbook()) {
            Sheet sheet = workbook.createSheet("Báo cáo doanh thu");

            // Font cho title
            org.apache.poi.ss.usermodel.Font titleFont = workbook.createFont();
            titleFont.setBold(true);
            titleFont.setFontHeightInPoints((short) 16);

            CellStyle titleStyle = workbook.createCellStyle();
            titleStyle.setFont(titleFont);
            titleStyle.setAlignment(HorizontalAlignment.CENTER);

            // Font cho normal
            org.apache.poi.ss.usermodel.Font normalFont = workbook.createFont();
            normalFont.setFontHeightInPoints((short) 12);

            CellStyle normalStyle = workbook.createCellStyle();
            normalStyle.setFont(normalFont);

            CellStyle headerStyle = workbook.createCellStyle();
            headerStyle.setFont(normalFont);
            headerStyle.setFillForegroundColor(IndexedColors.GREY_25_PERCENT.getIndex());
            headerStyle.setFillPattern(FillPatternType.SOLID_FOREGROUND);

            int rowNum = 0;

            // Title
            String loaiThongKe = (String) cmbLoaiThongKe.getSelectedItem();
            Row titleRow = sheet.createRow(rowNum++);
            Cell titleCell = titleRow.createCell(0);
            titleCell.setCellValue("Báo cáo theo " + loaiThongKe.toLowerCase());
            titleCell.setCellStyle(titleStyle);
            sheet.addMergedRegion(new org.apache.poi.ss.util.CellRangeAddress(0, 0, 0, 3));

            // Date created
            Row dateRow = sheet.createRow(rowNum++);
            Cell dateCell = dateRow.createCell(0);
            dateCell.setCellValue("Ngày tạo: " + java.time.LocalDateTime.now().format(DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss")));
            dateCell.setCellStyle(normalStyle);

            // Range info
            Row rangeRow = sheet.createRow(rowNum++);
            Cell rangeCell = rangeRow.createCell(0);
            String rangeText = "Thời gian từ ";
            if ("Theo ngày".equals(loaiThongKe)) {
                Date tuNgay = datePickerTuNgay.getDate();
                Date denNgay = datePickerDenNgay.getDate();
                rangeText += tuNgay.toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate().format(DateTimeFormatter.ofPattern("dd/MM/yyyy"));
                rangeText += " đến " + denNgay.toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate().format(DateTimeFormatter.ofPattern("dd/MM/yyyy"));
            } else if ("Theo tháng".equals(loaiThongKe)) {
                rangeText += cmbTuThang.getSelectedItem() + "/" + cmbTuNam.getSelectedItem();
                rangeText += " đến " + cmbDenThang.getSelectedItem() + "/" + cmbDenNam.getSelectedItem();
            } else if ("Theo quý".equals(loaiThongKe)) {
                rangeText += "Quý " + cmbTuQuy.getSelectedItem() + " năm " + cmbTuNam.getSelectedItem();
                rangeText += " đến Quý " + cmbDenQuy.getSelectedItem() + " năm " + cmbDenNam.getSelectedItem();
            } else if ("Theo năm".equals(loaiThongKe)) {
                rangeText += "Năm " + cmbTuNam.getSelectedItem();
                rangeText += " đến Năm " + cmbDenNam.getSelectedItem();
            }
            rangeCell.setCellValue(rangeText);
            rangeCell.setCellStyle(normalStyle);

            // Empty row
            rowNum++;

            // Headers
            Row headerRow = sheet.createRow(rowNum++);
            for (int i = 0; i < model.getColumnCount(); i++) {
                Cell cell = headerRow.createCell(i);
                cell.setCellValue(model.getColumnName(i));
                cell.setCellStyle(headerStyle);
            }

            // Data
            for (int i = 0; i < model.getRowCount(); i++) {
                Row row = sheet.createRow(rowNum++);
                for (int j = 0; j < model.getColumnCount(); j++) {
                    Cell cell = row.createCell(j);
                    cell.setCellValue(model.getValueAt(i, j).toString());
                    cell.setCellStyle(normalStyle);
                }
            }

            // Auto size columns
            for (int i = 0; i < model.getColumnCount(); i++) {
                sheet.autoSizeColumn(i);
            }

            // Write to file
            try (java.io.FileOutputStream fos = new java.io.FileOutputStream(file)) {
                workbook.write(fos);
            }

            JOptionPane.showMessageDialog(this, "Xuất file Excel thành công: " + file.getAbsolutePath(), "Thành công", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi khi xuất file: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Định dạng tiền như TraHangGUI
    private String dinhDangTien(double thanhTien) {
        DecimalFormat formatter = new DecimalFormat("#,###");
        return formatter.format(thanhTien) + " VNĐ";
    }

    // Get key cho HoaDon hoặc PhieuTraHang
    private String getKey(HoaDon hd, String loaiThongKe) {
        LocalDate date = hd.getNgayLapHoaDon().toLocalDate();
        if ("Theo ngày".equals(loaiThongKe)) {
            return date.format(DateTimeFormatter.ofPattern("dd/MM/yyyy"));
        } else if ("Theo tháng".equals(loaiThongKe)) {
            return String.format("%02d/%d", date.getMonthValue(), date.getYear());
        } else if ("Theo quý".equals(loaiThongKe)) {
            int quy = (date.getMonthValue() - 1) / 3 + 1;
            return "Quý " + quy + " năm " + date.getYear();
        } else if ("Theo năm".equals(loaiThongKe)) {
            return "Năm " + date.getYear();
        }
        return "";
    }

    private String getKey(PhieuTraHang pt, String loaiThongKe) {
        LocalDate date = pt.getNgayLapPhieuTraHang().toLocalDate();
        if ("Theo ngày".equals(loaiThongKe)) {
            return date.format(DateTimeFormatter.ofPattern("dd/MM/yyyy"));
        } else if ("Theo tháng".equals(loaiThongKe)) {
            return String.format("%02d/%d", date.getMonthValue(), date.getYear());
        } else if ("Theo quý".equals(loaiThongKe)) {
            int quy = (date.getMonthValue() - 1) / 3 + 1;
            return "Quý " + quy + " năm " + date.getYear();
        } else if ("Theo năm".equals(loaiThongKe)) {
            return "Năm " + date.getYear();
        }
        return "";
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
