/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package hethongnhathuocduocankhang.gui.baocao;

import hethongnhathuocduocankhang.dao.HoaDonDAO;
import hethongnhathuocduocankhang.dao.PhieuTraHangDAO;
import hethongnhathuocduocankhang.dao.BaoCaoDoanhThuDAO;
import hethongnhathuocduocankhang.entity.HoaDon;
import hethongnhathuocduocankhang.entity.PhieuTraHang;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyChangeListener;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.DecimalFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import java.util.Date;
import javax.swing.*;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.BorderStyle;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.HorizontalAlignment;
import org.apache.poi.ss.usermodel.IndexedColors;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.ss.util.CellRangeAddress;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.jdesktop.swingx.JXDatePicker;

/**
 *
 * @author MINH KHANG
 */
public class BaoCaoDoanhThu extends javax.swing.JPanel {

    private JXDatePicker datePickerTuNgay;
    private JXDatePicker datePickerDenNgay;
    private JComboBox<Integer> cmbTuThang;
    private JComboBox<Integer> cmbDenThang;
    private JComboBox<Integer> cmbTuQuy;
    private JComboBox<Integer> cmbDenQuy;
    private JComboBox<Integer> cmbTuNam;
    private JComboBox<Integer> cmbDenNam;
    private JComboBox<String> cmbLoaiThongKe;
    private JButton btnXemBaoCao;
    private JButton btnXuatFile;
    private JTable table;
    private DefaultTableModel model;
    private JLabel lblTongDoanhThu;
    private JScrollPane scrollPane;
    private JPanel pnlCenter;

    /**
     * Creates new form BaoCaoDoanhThu
     */
    public BaoCaoDoanhThu() {
        initComponents();
        setupUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void setupUI() {
        this.setLayout(new BorderLayout(10, 10));
        this.setBorder(new EmptyBorder(10, 10, 10, 10));

        // Panel NORTH (Bộ lọc báo cáo)
        JPanel pnlNorth = new JPanel();
        pnlNorth.setLayout(new BorderLayout());

        JPanel pnlFilter = new JPanel(new FlowLayout(FlowLayout.LEFT, 15, 5));
        pnlFilter.setBorder(new EmptyBorder(0, 0, 10, 0));

        Font fontLabel = new Font("Arial", Font.BOLD, 14);
        Font fontInput = new Font("Arial", Font.PLAIN, 14);
        
        JLabel lblTuThang = new JLabel("Từ tháng:");
        lblTuThang.setFont(fontLabel);

        JLabel lblDenThang = new JLabel("Đến tháng:");
        lblDenThang.setFont(fontLabel);

        JLabel lblTuQuy = new JLabel("Từ quý:");
        lblTuQuy.setFont(fontLabel);

        JLabel lblDenQuy = new JLabel("Đến quý:");
        lblDenQuy.setFont(fontLabel);

        JLabel lblTuNam = new JLabel("Từ năm:");
        lblTuNam.setFont(fontLabel);

        JLabel lblDenNam = new JLabel("Đến năm:");
        lblDenNam.setFont(fontLabel);

        JLabel lblTuNgay = new JLabel("Từ ngày:");
        lblTuNgay.setFont(fontLabel);
        datePickerTuNgay = new JXDatePicker();
        datePickerTuNgay.setFont(fontInput);
        datePickerTuNgay.setDate(java.util.Date.from(LocalDate.now().minusMonths(1).atStartOfDay(java.time.ZoneId.systemDefault()).toInstant())); // Mặc định 1 tháng trước

        // Ngăn chọn ngày lớn hơn ngày hiện tại
        PropertyChangeListener dateListenerTuNgay = evt -> {
            if ("date".equals(evt.getPropertyName())) {
                java.util.Date selectedDate = (java.util.Date) evt.getNewValue();
                if (selectedDate != null) {
                    LocalDate selectedLocalDate = LocalDate.ofInstant(selectedDate.toInstant(), java.time.ZoneId.systemDefault());
                    if (selectedLocalDate.isAfter(LocalDate.now())) {
                        datePickerTuNgay.setDate(java.util.Date.from(LocalDate.now().atStartOfDay(java.time.ZoneId.systemDefault()).toInstant()));
                    }
                }
            }
        };
        datePickerTuNgay.addPropertyChangeListener(dateListenerTuNgay);

        JLabel lblDenNgay = new JLabel("Đến ngày:");
        lblDenNgay.setFont(fontLabel);
        datePickerDenNgay = new JXDatePicker();
        datePickerDenNgay.setFont(fontInput);
        datePickerDenNgay.setDate(java.util.Date.from(LocalDate.now().atStartOfDay(java.time.ZoneId.systemDefault()).toInstant())); // Mặc định hôm nay

        // Ngăn chọn ngày lớn hơn ngày hiện tại
        PropertyChangeListener dateListenerDenNgay = evt -> {
            if ("date".equals(evt.getPropertyName())) {
                java.util.Date selectedDate = (java.util.Date) evt.getNewValue();
                if (selectedDate != null) {
                    LocalDate selectedLocalDate = LocalDate.ofInstant(selectedDate.toInstant(), java.time.ZoneId.systemDefault());
                    if (selectedLocalDate.isAfter(LocalDate.now())) {
                        datePickerDenNgay.setDate(java.util.Date.from(LocalDate.now().atStartOfDay(java.time.ZoneId.systemDefault()).toInstant()));
                    }
                }
            }
        };
        datePickerDenNgay.addPropertyChangeListener(dateListenerDenNgay);

        JLabel lblLoai = new JLabel("Loại thống kê:");
        lblLoai.setFont(fontLabel);
        String[] arrLoai = {"Theo ngày", "Theo tháng", "Theo quý", "Theo năm"};
        cmbLoaiThongKe = new JComboBox<>(arrLoai);
        cmbLoaiThongKe.setFont(fontInput);
        cmbLoaiThongKe.setPreferredSize(new Dimension(120, 30));
        cmbLoaiThongKe.addActionListener(e -> {
            String loai = (String) cmbLoaiThongKe.getSelectedItem();
            boolean isTheoNgay = "Theo ngày".equals(loai);
            boolean isTheoThang = "Theo tháng".equals(loai);
            boolean isTheoQuy = "Theo quý".equals(loai);
            boolean isTheoNam = "Theo năm".equals(loai);

            lblTuNgay.setVisible(isTheoNgay);
            datePickerTuNgay.setVisible(isTheoNgay);
            lblDenNgay.setVisible(isTheoNgay);
            datePickerDenNgay.setVisible(isTheoNgay);

            lblTuThang.setVisible(isTheoThang);
            cmbTuThang.setVisible(isTheoThang);
            lblDenThang.setVisible(isTheoThang);
            cmbDenThang.setVisible(isTheoThang);

            lblTuQuy.setVisible(isTheoQuy);
            cmbTuQuy.setVisible(isTheoQuy);
            lblDenQuy.setVisible(isTheoQuy);
            cmbDenQuy.setVisible(isTheoQuy);

            lblTuNam.setVisible(isTheoNam);
            cmbTuNam.setVisible(isTheoNam);
            lblDenNam.setVisible(isTheoNam);
            cmbDenNam.setVisible(isTheoNam);

            pnlFilter.revalidate();
            pnlFilter.repaint();

            // 👉 Reset table và tổng doanh thu
            model.setRowCount(0);
            lblTongDoanhThu.setText("Tổng doanh thu: 0 VND");
        });

        // Mặc định chọn "Theo ngày" và hiện JDatePicker
        // cmbLoaiThongKe.setSelectedItem("Theo ngày");
        // lblTuNgay.setVisible(true);
        // datePickerTuNgay.setVisible(true);
        // lblDenNgay.setVisible(true);
        // datePickerDenNgay.setVisible(true);

        // Tạo combo tháng
        cmbTuThang = new JComboBox<>();
        for (int i = 1; i <= 12; i++) cmbTuThang.addItem(i);
        cmbTuThang.setFont(fontInput);
        cmbTuThang.setPreferredSize(new Dimension(80, 30));

        cmbDenThang = new JComboBox<>();
        for (int i = 1; i <= 12; i++) cmbDenThang.addItem(i);
        cmbDenThang.setFont(fontInput);
        cmbDenThang.setPreferredSize(new Dimension(80, 30));

        // Tạo combo quý
        cmbTuQuy = new JComboBox<>();
        for (int i = 1; i <= 4; i++) cmbTuQuy.addItem(i);
        cmbTuQuy.setFont(fontInput);
        cmbTuQuy.setPreferredSize(new Dimension(80, 30));

        cmbDenQuy = new JComboBox<>();
        for (int i = 1; i <= 4; i++) cmbDenQuy.addItem(i);
        cmbDenQuy.setFont(fontInput);
        cmbDenQuy.setPreferredSize(new Dimension(80, 30));

        int minYear = 2025;
        int maxYear = LocalDate.now().getYear();
        cmbTuNam = new JComboBox<>();
        for (int i = minYear; i <= maxYear; i++) cmbTuNam.addItem(i);
        cmbTuNam.setFont(fontInput);
        cmbTuNam.setPreferredSize(new Dimension(80, 30));

        cmbDenNam = new JComboBox<>();
        for (int i = minYear; i <= maxYear; i++) cmbDenNam.addItem(i);
        cmbDenNam.setFont(fontInput);
        cmbDenNam.setPreferredSize(new Dimension(80, 30));

        // Ẩn tất cả ban đầu
        datePickerTuNgay.setVisible(false);
        datePickerDenNgay.setVisible(false);
        cmbTuThang.setVisible(false);
        cmbDenThang.setVisible(false);
        cmbTuQuy.setVisible(false);
        cmbDenQuy.setVisible(false);
        cmbTuNam.setVisible(false);
        cmbDenNam.setVisible(false);

        btnXemBaoCao = new JButton("Xem báo cáo");
        btnXemBaoCao.setFont(fontLabel);
        btnXemBaoCao.setBackground(new Color(25,118,210));
        btnXemBaoCao.setForeground(new Color(255,255,255));
        btnXemBaoCao.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                xemBaoCao();
            }
        });

        btnXuatFile = new JButton("Xuất file báo cáo");
        btnXuatFile.setFont(fontLabel);
        btnXuatFile.setBackground(new Color(0,203,0));
        btnXuatFile.setForeground(new Color(255,255,255));
        btnXuatFile.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JFileChooser fileChooser = new JFileChooser();
                fileChooser.setDialogTitle("Chọn nơi lưu báo cáo Excel");
                fileChooser.setSelectedFile(new File("BaoCao.xlsx"));
                int userSelection = fileChooser.showSaveDialog(null);

                if (userSelection == JFileChooser.APPROVE_OPTION) {
                    File fileToSave = fileChooser.getSelectedFile();
                    // Gọi phương thức xuất báo cáo
                    xuatFileBaoCao(fileToSave);
                }

            }
        });
        // TODO: Thêm logic xuất file sau

        pnlFilter.add(lblTuNgay);
        pnlFilter.add(datePickerTuNgay);
        pnlFilter.add(lblDenNgay);
        pnlFilter.add(datePickerDenNgay);
        
        pnlFilter.add(lblTuThang);
        pnlFilter.add(cmbTuThang);
        pnlFilter.add(lblDenThang);
        pnlFilter.add(cmbDenThang);

        pnlFilter.add(lblTuQuy);
        pnlFilter.add(cmbTuQuy);
        pnlFilter.add(lblDenQuy);
        pnlFilter.add(cmbDenQuy);

        pnlFilter.add(lblTuNam);
        pnlFilter.add(cmbTuNam);
        pnlFilter.add(lblDenNam);
        pnlFilter.add(cmbDenNam);
        
        pnlFilter.add(lblLoai);
        pnlFilter.add(cmbLoaiThongKe);
        pnlFilter.add(btnXemBaoCao);
        pnlFilter.add(btnXuatFile);

        pnlNorth.add(pnlFilter, BorderLayout.CENTER);

        // Panel CENTER (Table)
        pnlCenter = new JPanel(new BorderLayout());
        String[] columnNames = {"Thời gian", "Tổng hóa đơn", "Tổng phiếu trả", "Doanh thu"};
        model = new DefaultTableModel(columnNames, 0);
        table = new JTable(model);
        table.setFont(new Font("Arial", Font.PLAIN, 14));
        table.getTableHeader().setFont(new Font("Arial", Font.BOLD, 14));
        scrollPane = new JScrollPane(table);
        pnlCenter.add(scrollPane, BorderLayout.CENTER);

        // Panel SOUTH (Tổng doanh thu)
        JPanel pnlSouth = new JPanel(new FlowLayout(FlowLayout.RIGHT));
        lblTongDoanhThu = new JLabel("Tổng doanh thu: 0 VND");
        lblTongDoanhThu.setFont(new Font("Arial", Font.BOLD, 16));
        pnlSouth.add(lblTongDoanhThu);

        // Thêm vào main panel
        this.add(pnlNorth, BorderLayout.NORTH);
        this.add(pnlCenter, BorderLayout.CENTER);
        this.add(pnlSouth, BorderLayout.SOUTH);

        // Xóa các component cũ nếu có

        // Mặc định chọn "Theo ngày" và hiện JDatePicker
        cmbLoaiThongKe.setSelectedItem("Theo ngày");
        lblTuNgay.setVisible(true);
        datePickerTuNgay.setVisible(true);
        lblDenNgay.setVisible(true);
        datePickerDenNgay.setVisible(true);
    }

    private void xemBaoCao() {
        showLoadingDialog();

        // 1. Sửa SwingWorker để trả về Map (Key, Value) thay vì Void
        SwingWorker<Map<String, double[]>, Void> worker = new SwingWorker<>() {

            // Khai báo biến này ở đây để dùng chung cho cả doInBackground và done
            List<String> allKeys = new ArrayList<>();

            @Override
            protected Map<String, double[]> doInBackground() throws Exception {
                String loaiThongKe = (String) cmbLoaiThongKe.getSelectedItem();

                // Khai báo biến ngày để gửi xuống DB
                java.util.Date dbTuNgay = null;
                java.util.Date dbDenNgay = null;

                // --- XỬ LÝ NGÀY THÁNG (Logic giữ nguyên như cũ) ---
                if ("Theo ngày".equals(loaiThongKe)) {
                    dbTuNgay = datePickerTuNgay.getDate();
                    dbDenNgay = datePickerDenNgay.getDate();

                    if (dbTuNgay.after(dbDenNgay)) {
                        throw new Exception("Từ ngày phải bé hơn đến ngày");
                    }

                    LocalDate startDate = dbTuNgay.toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();
                    LocalDate endDate = dbDenNgay.toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();
                    for (LocalDate date = startDate; !date.isAfter(endDate); date = date.plusDays(1)) {
                        allKeys.add(date.format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));
                    }

                } else if ("Theo tháng".equals(loaiThongKe)) {
                    int tuThang = (Integer) cmbTuThang.getSelectedItem();
                    int tuNam = (Integer) cmbTuNam.getSelectedItem();
                    int denThang = (Integer) cmbDenThang.getSelectedItem();
                    int denNam = (Integer) cmbDenNam.getSelectedItem();

                    dbTuNgay = java.sql.Date.valueOf(LocalDate.of(tuNam, tuThang, 1));
                    LocalDate lastDayOfMonth = LocalDate.of(denNam, denThang, 1).plusMonths(1).minusDays(1);
                    dbDenNgay = java.sql.Date.valueOf(lastDayOfMonth);

                    for (int nam = tuNam; nam <= denNam; nam++) {
                        int startThang = (nam == tuNam) ? tuThang : 1;
                        int endThang = (nam == denNam) ? denThang : 12;
                        for (int thang = startThang; thang <= endThang; thang++) {
                            allKeys.add(String.format("%02d/%d", thang, nam));
                        }
                    }
                } else if ("Theo quý".equals(loaiThongKe)) {
                    int tuQuy = (Integer) cmbTuQuy.getSelectedItem();
                    int tuNam = (Integer) cmbTuNam.getSelectedItem();
                    int denQuy = (Integer) cmbDenQuy.getSelectedItem();
                    int denNam = (Integer) cmbDenNam.getSelectedItem();

                    int startMonth = (tuQuy - 1) * 3 + 1;
                    dbTuNgay = java.sql.Date.valueOf(LocalDate.of(tuNam, startMonth, 1));

                    int endMonth = denQuy * 3;
                    LocalDate lastDayOfQuarter = LocalDate.of(denNam, endMonth, 1).plusMonths(1).minusDays(1);
                    dbDenNgay = java.sql.Date.valueOf(lastDayOfQuarter);

                    for (int nam = tuNam; nam <= denNam; nam++) {
                        int startQuy = (nam == tuNam) ? tuQuy : 1;
                        int endQuy = (nam == denNam) ? denQuy : 4;
                        for (int quy = startQuy; quy <= endQuy; quy++) {
                            allKeys.add("Quý " + quy + " năm " + nam);
                        }
                    }
                } else if ("Theo năm".equals(loaiThongKe)) {
                    int tuNam = (Integer) cmbTuNam.getSelectedItem();
                    int denNam = (Integer) cmbDenNam.getSelectedItem();

                    dbTuNgay = java.sql.Date.valueOf(LocalDate.of(tuNam, 1, 1));
                    dbDenNgay = java.sql.Date.valueOf(LocalDate.of(denNam, 12, 31));

                    for (int nam = tuNam; nam <= denNam; nam++) {
                        allKeys.add("Năm " + nam);
                    }
                }

                // --- GỌI DAO ---
                // Chỉ lấy dữ liệu, KHÔNG cập nhật giao diện ở đây
                BaoCaoDoanhThuDAO thongKeDAO = new BaoCaoDoanhThuDAO();
                return thongKeDAO.getDoanhThuMap(dbTuNgay, dbDenNgay, loaiThongKe);
            }

            @Override
            protected void done() {
                try {
                    // Lấy kết quả từ doInBackground (nếu có lỗi nó sẽ ném ra ở đây)
                    Map<String, double[]> dataMap = get();

                    // --- CẬP NHẬT GIAO DIỆN Ở ĐÂY (An toàn tuyệt đối) ---
                    model.setRowCount(0);
                    double tongDoanhThuToanBo = 0;

                    for (String key : allKeys) {
                        double tongHD = 0;
                        double tongPT = 0;

                        if (dataMap.containsKey(key)) {
                            double[] values = dataMap.get(key);
                            tongHD = values[0];
                            tongPT = values[1];
                        }

                        double doanhThu = tongHD - tongPT;

                        model.addRow(new Object[]{key, dinhDangTien(tongHD), dinhDangTien(tongPT), dinhDangTien(doanhThu)});
                        tongDoanhThuToanBo += doanhThu;
                    }
                    lblTongDoanhThu.setText("Tổng doanh thu: " + dinhDangTien(tongDoanhThuToanBo));

                } catch (Exception e) {
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(null, "Có lỗi xảy ra: " + e.getMessage());
                } finally {
                    // --- QUAN TRỌNG: LUÔN TẮT LOADING DÙ CÓ LỖI HAY KHÔNG ---
                    disposeLoadingDialog();
                }
            }
        };
        worker.execute();
    }

    // Định dạng tiền như TraHangGUI
    private String dinhDangTien(double thanhTien) {
        DecimalFormat formatter = new DecimalFormat("#,###");
        return formatter.format(thanhTien) + " VNĐ";
    }

    // Get key cho HoaDon hoặc PhieuTraHang
    private String getKey(HoaDon hd, String loaiThongKe) {
        LocalDate date = hd.getNgayLapHoaDon().toLocalDate();
        if ("Theo ngày".equals(loaiThongKe)) {
            return date.format(DateTimeFormatter.ofPattern("dd/MM/yyyy"));
        } else if ("Theo tháng".equals(loaiThongKe)) {
            return String.format("%02d/%d", date.getMonthValue(), date.getYear());
        } else if ("Theo quý".equals(loaiThongKe)) {
            int quy = (date.getMonthValue() - 1) / 3 + 1;
            return "Quý " + quy + " năm " + date.getYear();
        } else if ("Theo năm".equals(loaiThongKe)) {
            return "Năm " + date.getYear();
        }
        return "";
    }

    private String getKey(PhieuTraHang pt, String loaiThongKe) {
        LocalDate date = pt.getNgayLapPhieuTraHang().toLocalDate();
        if ("Theo ngày".equals(loaiThongKe)) {
            return date.format(DateTimeFormatter.ofPattern("dd/MM/yyyy"));
        } else if ("Theo tháng".equals(loaiThongKe)) {
            return String.format("%02d/%d", date.getMonthValue(), date.getYear());
        } else if ("Theo quý".equals(loaiThongKe)) {
            int quy = (date.getMonthValue() - 1) / 3 + 1;
            return "Quý " + quy + " năm " + date.getYear();
        } else if ("Theo năm".equals(loaiThongKe)) {
            return "Năm " + date.getYear();
        }
        return "";
    }

    private JDialog loadingDialog;

    private void showLoadingDialog() {
        loadingDialog = new JDialog(
            (java.awt.Frame) SwingUtilities.getWindowAncestor(this),
            "Đang tải", 
            false
        );
        loadingDialog.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);

        // Panel chứa label + progress bar
        JPanel panel = new JPanel(new BorderLayout(10, 10));
        JLabel label = new JLabel("Đang thống kê dữ liệu...", SwingConstants.CENTER);
        label.setFont(new Font("Arial", Font.BOLD, 14));
        panel.add(label, BorderLayout.NORTH);

        // Thanh loading
        JProgressBar progressBar = new JProgressBar();
        progressBar.setIndeterminate(true); // chạy qua lại
        panel.add(progressBar, BorderLayout.CENTER);

        loadingDialog.getContentPane().add(panel);
        loadingDialog.pack(); // tự động tính kích thước
        loadingDialog.setLocationRelativeTo(this);

        this.setEnabled(false);
        loadingDialog.setVisible(true);
    }

    private void disposeLoadingDialog() {
        if (loadingDialog != null) {
            loadingDialog.dispose();
            loadingDialog = null;
        }
        this.setEnabled(true);
    }
    
    private void xuatFileBaoCao(File fileToSave) {
        // 1. Kiểm tra bảng có dữ liệu không
        if (model.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Chưa có dữ liệu để xuất. Vui lòng ấn 'Xem báo cáo' trước!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 2. Tự động thêm đuôi .xlsx nếu người dùng quên
        String path = fileToSave.getAbsolutePath();
        if (!path.toLowerCase().endsWith(".xlsx")) {
            fileToSave = new File(path + ".xlsx");
        }

        try (Workbook workbook = new XSSFWorkbook()) {
            Sheet sheet = workbook.createSheet("Báo cáo");

            String loaiThongKe = (String) cmbLoaiThongKe.getSelectedItem();

            // --- STYLE ---
            CellStyle headerStyle = workbook.createCellStyle();
            org.apache.poi.ss.usermodel.Font headerFont = workbook.createFont();
            headerFont.setBold(true);
            headerFont.setFontHeightInPoints((short) 16);
            headerStyle.setFont(headerFont);
            headerStyle.setAlignment(HorizontalAlignment.CENTER);

            CellStyle borderStyle = workbook.createCellStyle();
            borderStyle.setBorderTop(BorderStyle.THIN);
            borderStyle.setBorderBottom(BorderStyle.THIN);
            borderStyle.setBorderLeft(BorderStyle.THIN);
            borderStyle.setBorderRight(BorderStyle.THIN);

            // --- ROW 0: TIÊU ĐỀ ---
            Row headerRow = sheet.createRow(0);
            Cell headerCell = headerRow.createCell(0);
            headerCell.setCellValue("BÁO CÁO DOANH THU " + loaiThongKe.toUpperCase());
            headerCell.setCellStyle(headerStyle);

            // Merge cell tiêu đề (tránh lỗi nếu cột < 1)
            if (model.getColumnCount() > 0) {
                sheet.addMergedRegion(new CellRangeAddress(0, 0, 0, model.getColumnCount() - 1));
            }

            // --- ROW 2: THỜI GIAN THỐNG KÊ ---
            Row infoRow = sheet.createRow(2);
            Cell infoCell = infoRow.createCell(0);
            String thoiGianText = "";

            if ("Theo ngày".equals(loaiThongKe)) {
                DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy");
                LocalDate d1 = datePickerTuNgay.getDate().toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();
                LocalDate d2 = datePickerDenNgay.getDate().toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();
                thoiGianText = "Từ ngày " + d1.format(dtf) + " đến ngày " + d2.format(dtf);
            } else if ("Theo tháng".equals(loaiThongKe)) {
                thoiGianText = "Từ tháng " + cmbTuThang.getSelectedItem() + "/" + cmbTuNam.getSelectedItem() + 
                               " đến tháng " + cmbDenThang.getSelectedItem() + "/" + cmbDenNam.getSelectedItem();
            } else if ("Theo quý".equals(loaiThongKe)) {
                thoiGianText = "Từ quý " + cmbTuQuy.getSelectedItem() + " năm " + cmbTuNam.getSelectedItem() + 
                               " đến quý " + cmbDenQuy.getSelectedItem() + " năm " + cmbDenNam.getSelectedItem();
            } else if ("Theo năm".equals(loaiThongKe)) {
                thoiGianText = "Từ năm " + cmbTuNam.getSelectedItem() + " đến năm " + cmbDenNam.getSelectedItem();
            }

            infoCell.setCellValue(thoiGianText);
            if (model.getColumnCount() > 0) {
                sheet.addMergedRegion(new CellRangeAddress(2, 2, 0, model.getColumnCount() - 1));
            }

            // --- ROW 3: NGÀY LẬP ---
            Row timeRow = sheet.createRow(3);
            Cell timeCell = timeRow.createCell(0);
            String ngayLap = java.time.LocalDateTime.now().format(DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm"));
            timeCell.setCellValue("Thời gian lập báo cáo: " + ngayLap);
            if (model.getColumnCount() > 0) {
                sheet.addMergedRegion(new CellRangeAddress(3, 3, 0, model.getColumnCount() - 1));
            }

            // --- ROW 5: HEADER BẢNG ---
            Row tableHeaderRow = sheet.createRow(5);
            for (int i = 0; i < model.getColumnCount(); i++) {
                Cell cell = tableHeaderRow.createCell(i);
                cell.setCellValue(model.getColumnName(i));
                cell.setCellStyle(borderStyle);
            }

            // --- DATA ROWS ---
            for (int r = 0; r < model.getRowCount(); r++) {
                Row row = sheet.createRow(r + 6);
                for (int c = 0; c < model.getColumnCount(); c++) {
                    Object value = model.getValueAt(r, c);
                    Cell cell = row.createCell(c);
                    cell.setCellValue(value != null ? value.toString() : "");
                    cell.setCellStyle(borderStyle);
                }
            }

            // --- FOOTER: TỔNG DOANH THU ---
            int footerRowIndex = model.getRowCount() + 7;
            Row footerRow = sheet.createRow(footerRowIndex);
            Cell footerCell = footerRow.createCell(0);
            footerCell.setCellValue(lblTongDoanhThu.getText());
            CellStyle footerStyle = workbook.createCellStyle();
            org.apache.poi.ss.usermodel.Font footerFont = workbook.createFont();
            footerFont.setBold(true);
            footerFont.setColor(IndexedColors.RED.getIndex());
            footerStyle.setFont(footerFont);
            footerCell.setCellStyle(footerStyle);

            if (model.getColumnCount() > 0) {
                sheet.addMergedRegion(new CellRangeAddress(footerRowIndex, footerRowIndex, 0, model.getColumnCount() - 1));
            }

            // Auto resize column
            for (int i = 0; i < model.getColumnCount(); i++) {
                sheet.autoSizeColumn(i);
            }

            // Ghi file
            try (FileOutputStream fos = new FileOutputStream(fileToSave)) {
                workbook.write(fos);
                JOptionPane.showMessageDialog(this, "Xuất báo cáo thành công!\nLưu tại: " + fileToSave.getAbsolutePath());

                // Tùy chọn: Mở file ngay sau khi xuất
                // Desktop.getDesktop().open(fileToSave); 
            }

        } catch (java.io.FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Lỗi: File đang được mở bởi chương trình khác.\nVui lòng đóng file Excel lại và thử lại!", "Lỗi file", JOptionPane.ERROR_MESSAGE);
        } catch (IOException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi ghi file: " + ex.getMessage(), "Lỗi IO", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi không xác định: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
