/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package hethongnhathuocduocankhang.gui.baocao;

import hethongnhathuocduocankhang.dao.HoaDonDAO;
import hethongnhathuocduocankhang.dao.PhieuTraHangDAO;
import hethongnhathuocduocankhang.entity.HoaDon;
import hethongnhathuocduocankhang.entity.PhieuTraHang;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyChangeListener;
import java.text.DecimalFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import java.util.Date;
import javax.swing.*;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.JXDatePicker;

/**
 *
 * @author MINH KHANG
 */
public class BaoCaoDoanhThu extends javax.swing.JPanel {

    private JXDatePicker datePickerTuNgay;
    private JXDatePicker datePickerDenNgay;
    private JComboBox<Integer> cmbTuThang;
    private JComboBox<Integer> cmbDenThang;
    private JComboBox<Integer> cmbTuQuy;
    private JComboBox<Integer> cmbDenQuy;
    private JComboBox<Integer> cmbTuNam;
    private JComboBox<Integer> cmbDenNam;
    private JComboBox<String> cmbLoaiThongKe;
    private JButton btnXemBaoCao;
    private JButton btnXuatFile;
    private JTable table;
    private DefaultTableModel model;
    private JLabel lblTongDoanhThu;
    private JScrollPane scrollPane;
    private JPanel pnlCenter;

    /**
     * Creates new form BaoCaoDoanhThu
     */
    public BaoCaoDoanhThu() {
        initComponents();
        setupUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel2.add(jScrollPane2);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void setupUI() {
        this.setLayout(new BorderLayout(10, 10));
        this.setBorder(new EmptyBorder(10, 10, 10, 10));

        // Panel NORTH (Bộ lọc báo cáo)
        JPanel pnlNorth = new JPanel();
        pnlNorth.setLayout(new BorderLayout());

        JPanel pnlFilter = new JPanel(new FlowLayout(FlowLayout.LEFT, 15, 5));
        pnlFilter.setBorder(new EmptyBorder(0, 0, 10, 0));

        Font fontLabel = new Font("Arial", Font.BOLD, 14);
        Font fontInput = new Font("Arial", Font.PLAIN, 14);
        
        JLabel lblTuThang = new JLabel("Từ tháng:");
        lblTuThang.setFont(fontLabel);

        JLabel lblDenThang = new JLabel("Đến tháng:");
        lblDenThang.setFont(fontLabel);

        JLabel lblTuQuy = new JLabel("Từ quý:");
        lblTuQuy.setFont(fontLabel);

        JLabel lblDenQuy = new JLabel("Đến quý:");
        lblDenQuy.setFont(fontLabel);

        JLabel lblTuNam = new JLabel("Từ năm:");
        lblTuNam.setFont(fontLabel);

        JLabel lblDenNam = new JLabel("Đến năm:");
        lblDenNam.setFont(fontLabel);

        JLabel lblTuNgay = new JLabel("Từ ngày:");
        lblTuNgay.setFont(fontLabel);
        datePickerTuNgay = new JXDatePicker();
        datePickerTuNgay.setFont(fontInput);
        datePickerTuNgay.setDate(java.util.Date.from(LocalDate.now().minusMonths(1).atStartOfDay(java.time.ZoneId.systemDefault()).toInstant())); // Mặc định 1 tháng trước

        // Ngăn chọn ngày lớn hơn ngày hiện tại
        PropertyChangeListener dateListenerTuNgay = evt -> {
            if ("date".equals(evt.getPropertyName())) {
                java.util.Date selectedDate = (java.util.Date) evt.getNewValue();
                if (selectedDate != null) {
                    LocalDate selectedLocalDate = LocalDate.ofInstant(selectedDate.toInstant(), java.time.ZoneId.systemDefault());
                    if (selectedLocalDate.isAfter(LocalDate.now())) {
                        datePickerTuNgay.setDate(java.util.Date.from(LocalDate.now().atStartOfDay(java.time.ZoneId.systemDefault()).toInstant()));
                    }
                }
            }
        };
        datePickerTuNgay.addPropertyChangeListener(dateListenerTuNgay);

        JLabel lblDenNgay = new JLabel("Đến ngày:");
        lblDenNgay.setFont(fontLabel);
        datePickerDenNgay = new JXDatePicker();
        datePickerDenNgay.setFont(fontInput);
        datePickerDenNgay.setDate(java.util.Date.from(LocalDate.now().atStartOfDay(java.time.ZoneId.systemDefault()).toInstant())); // Mặc định hôm nay

        // Ngăn chọn ngày lớn hơn ngày hiện tại
        PropertyChangeListener dateListenerDenNgay = evt -> {
            if ("date".equals(evt.getPropertyName())) {
                java.util.Date selectedDate = (java.util.Date) evt.getNewValue();
                if (selectedDate != null) {
                    LocalDate selectedLocalDate = LocalDate.ofInstant(selectedDate.toInstant(), java.time.ZoneId.systemDefault());
                    if (selectedLocalDate.isAfter(LocalDate.now())) {
                        datePickerDenNgay.setDate(java.util.Date.from(LocalDate.now().atStartOfDay(java.time.ZoneId.systemDefault()).toInstant()));
                    }
                }
            }
        };
        datePickerDenNgay.addPropertyChangeListener(dateListenerDenNgay);

        JLabel lblLoai = new JLabel("Loại thống kê:");
        lblLoai.setFont(fontLabel);
        String[] arrLoai = {"Theo ngày", "Theo tháng", "Theo quý", "Theo năm"};
        cmbLoaiThongKe = new JComboBox<>(arrLoai);
        cmbLoaiThongKe.setFont(fontInput);
        cmbLoaiThongKe.setPreferredSize(new Dimension(120, 30));
        cmbLoaiThongKe.addActionListener(e -> {
            String loai = (String) cmbLoaiThongKe.getSelectedItem();
            boolean isTheoNgay = "Theo ngày".equals(loai);
            boolean isTheoThang = "Theo tháng".equals(loai);
            boolean isTheoQuy = "Theo quý".equals(loai);
            boolean isTheoNam = "Theo năm".equals(loai);

            lblTuNgay.setVisible(isTheoNgay);
            datePickerTuNgay.setVisible(isTheoNgay);
            lblDenNgay.setVisible(isTheoNgay);
            datePickerDenNgay.setVisible(isTheoNgay);

            lblTuThang.setVisible(isTheoThang);
            cmbTuThang.setVisible(isTheoThang);
            lblDenThang.setVisible(isTheoThang);
            cmbDenThang.setVisible(isTheoThang);

            lblTuQuy.setVisible(isTheoQuy);
            cmbTuQuy.setVisible(isTheoQuy);
            lblDenQuy.setVisible(isTheoQuy);
            cmbDenQuy.setVisible(isTheoQuy);

            lblTuNam.setVisible(isTheoNam);
            cmbTuNam.setVisible(isTheoNam);
            lblDenNam.setVisible(isTheoNam);
            cmbDenNam.setVisible(isTheoNam);

            pnlFilter.revalidate();
            pnlFilter.repaint();
        });

        // Mặc định chọn "Theo ngày" và hiện JDatePicker
        // cmbLoaiThongKe.setSelectedItem("Theo ngày");
        // lblTuNgay.setVisible(true);
        // datePickerTuNgay.setVisible(true);
        // lblDenNgay.setVisible(true);
        // datePickerDenNgay.setVisible(true);

        // Tạo combo tháng
        cmbTuThang = new JComboBox<>();
        for (int i = 1; i <= 12; i++) cmbTuThang.addItem(i);
        cmbTuThang.setFont(fontInput);
        cmbTuThang.setPreferredSize(new Dimension(80, 30));

        cmbDenThang = new JComboBox<>();
        for (int i = 1; i <= 12; i++) cmbDenThang.addItem(i);
        cmbDenThang.setFont(fontInput);
        cmbDenThang.setPreferredSize(new Dimension(80, 30));

        // Tạo combo quý
        cmbTuQuy = new JComboBox<>();
        for (int i = 1; i <= 4; i++) cmbTuQuy.addItem(i);
        cmbTuQuy.setFont(fontInput);
        cmbTuQuy.setPreferredSize(new Dimension(80, 30));

        cmbDenQuy = new JComboBox<>();
        for (int i = 1; i <= 4; i++) cmbDenQuy.addItem(i);
        cmbDenQuy.setFont(fontInput);
        cmbDenQuy.setPreferredSize(new Dimension(80, 30));

        int minYear = 2025;
        int maxYear = LocalDate.now().getYear();
        cmbTuNam = new JComboBox<>();
        for (int i = minYear; i <= maxYear; i++) cmbTuNam.addItem(i);
        cmbTuNam.setFont(fontInput);
        cmbTuNam.setPreferredSize(new Dimension(80, 30));

        cmbDenNam = new JComboBox<>();
        for (int i = minYear; i <= maxYear; i++) cmbDenNam.addItem(i);
        cmbDenNam.setFont(fontInput);
        cmbDenNam.setPreferredSize(new Dimension(80, 30));

        // Ẩn tất cả ban đầu
        datePickerTuNgay.setVisible(false);
        datePickerDenNgay.setVisible(false);
        cmbTuThang.setVisible(false);
        cmbDenThang.setVisible(false);
        cmbTuQuy.setVisible(false);
        cmbDenQuy.setVisible(false);
        cmbTuNam.setVisible(false);
        cmbDenNam.setVisible(false);

        btnXemBaoCao = new JButton("Xem báo cáo");
        btnXemBaoCao.setFont(fontLabel);
        btnXemBaoCao.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                xemBaoCao();
            }
        });

        btnXuatFile = new JButton("Xuất file báo cáo");
        btnXuatFile.setFont(fontLabel);
        // TODO: Thêm logic xuất file sau

        pnlFilter.add(lblTuNgay);
        pnlFilter.add(datePickerTuNgay);
        pnlFilter.add(lblDenNgay);
        pnlFilter.add(datePickerDenNgay);
        
        pnlFilter.add(lblTuThang);
        pnlFilter.add(cmbTuThang);
        pnlFilter.add(lblDenThang);
        pnlFilter.add(cmbDenThang);

        pnlFilter.add(lblTuQuy);
        pnlFilter.add(cmbTuQuy);
        pnlFilter.add(lblDenQuy);
        pnlFilter.add(cmbDenQuy);

        pnlFilter.add(lblTuNam);
        pnlFilter.add(cmbTuNam);
        pnlFilter.add(lblDenNam);
        pnlFilter.add(cmbDenNam);
        
        pnlFilter.add(lblLoai);
        pnlFilter.add(cmbLoaiThongKe);
        pnlFilter.add(btnXemBaoCao);
        pnlFilter.add(btnXuatFile);

        pnlNorth.add(pnlFilter, BorderLayout.CENTER);

        // Panel CENTER (Table)
        pnlCenter = new JPanel(new BorderLayout());
        String[] columnNames = {"Thời gian", "Tổng hóa đơn", "Tổng phiếu trả", "Doanh thu"};
        model = new DefaultTableModel(columnNames, 0);
        table = new JTable(model);
        table.setFont(new Font("Arial", Font.PLAIN, 14));
        table.getTableHeader().setFont(new Font("Arial", Font.BOLD, 14));
        scrollPane = new JScrollPane(table);
        pnlCenter.add(scrollPane, BorderLayout.CENTER);

        // Panel SOUTH (Tổng doanh thu)
        JPanel pnlSouth = new JPanel(new FlowLayout(FlowLayout.RIGHT));
        lblTongDoanhThu = new JLabel("Tổng doanh thu: 0 VND");
        lblTongDoanhThu.setFont(new Font("Arial", Font.BOLD, 16));
        pnlSouth.add(lblTongDoanhThu);

        // Thêm vào main panel
        this.add(pnlNorth, BorderLayout.NORTH);
        this.add(pnlCenter, BorderLayout.CENTER);
        this.add(pnlSouth, BorderLayout.SOUTH);

        // Xóa các component cũ nếu có
        this.remove(jPanel1);
        this.remove(jPanel2);

        // Mặc định chọn "Theo ngày" và hiện JDatePicker
        cmbLoaiThongKe.setSelectedItem("Theo ngày");
        lblTuNgay.setVisible(true);
        datePickerTuNgay.setVisible(true);
        lblDenNgay.setVisible(true);
        datePickerDenNgay.setVisible(true);
    }

    private void xemBaoCao() {
    // Show loading
    showLoadingDialog();

    SwingWorker<Void, Void> worker = new SwingWorker<>() {
        @Override
        protected Void doInBackground() throws Exception {
            try {
                String loaiThongKe = (String) cmbLoaiThongKe.getSelectedItem();

                // Query DB
                HoaDonDAO hoaDonDAO = new HoaDonDAO();
                PhieuTraHangDAO phieuTraDAO = new PhieuTraHangDAO();

                ArrayList<HoaDon> hoaDons = hoaDonDAO.getAllHoaDon();
                ArrayList<PhieuTraHang> phieuTras = phieuTraDAO.getAllPhieuTraHang();

                // Tạo list tất cả khoảng thời gian trong range
                List<String> allKeys = new ArrayList<>();
                if ("Theo ngày".equals(loaiThongKe)) {
                    Date tuNgay = datePickerTuNgay.getDate();
                    Date denNgay = datePickerDenNgay.getDate();
                    LocalDate startDate = tuNgay.toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();
                    LocalDate endDate = denNgay.toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();
                    for (LocalDate date = startDate; !date.isAfter(endDate); date = date.plusDays(1)) {
                        allKeys.add(date.format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));
                    }
                } else if ("Theo tháng".equals(loaiThongKe)) {
                    int tuThang = (Integer) cmbTuThang.getSelectedItem();
                    int tuNam = (Integer) cmbTuNam.getSelectedItem();
                    int denThang = (Integer) cmbDenThang.getSelectedItem();
                    int denNam = (Integer) cmbDenNam.getSelectedItem();
                    for (int nam = tuNam; nam <= denNam; nam++) {
                        int startThang = (nam == tuNam) ? tuThang : 1;
                        int endThang = (nam == denNam) ? denThang : 12;
                        for (int thang = startThang; thang <= endThang; thang++) {
                            allKeys.add(String.format("%02d/%d", thang, nam));
                        }
                    }
                } else if ("Theo quý".equals(loaiThongKe)) {
                    int tuQuy = (Integer) cmbTuQuy.getSelectedItem();
                    int tuNam = (Integer) cmbTuNam.getSelectedItem();
                    int denQuy = (Integer) cmbDenQuy.getSelectedItem();
                    int denNam = (Integer) cmbDenNam.getSelectedItem();
                    for (int nam = tuNam; nam <= denNam; nam++) {
                        int startQuy = (nam == tuNam) ? tuQuy : 1;
                        int endQuy = (nam == denNam) ? denQuy : 4;
                        for (int quy = startQuy; quy <= endQuy; quy++) {
                            allKeys.add("Quý " + quy + " năm " + nam);
                        }
                    }
                } else if ("Theo năm".equals(loaiThongKe)) {
                    int tuNam = (Integer) cmbTuNam.getSelectedItem();
                    int denNam = (Integer) cmbDenNam.getSelectedItem();
                    for (int nam = tuNam; nam <= denNam; nam++) {
                        allKeys.add("Năm " + nam);
                    }
                }

                // Tính doanh thu và cập nhật table
                model.setRowCount(0);
                double tongDoanhThu = 0;

                for (String key : allKeys) {
                    double tongHD = hoaDons.stream()
                        .filter(hd -> getKey(hd, loaiThongKe).equals(key))
                        .mapToDouble(HoaDon::getTongTien)
                        .sum();
                    double tongPT = phieuTras.stream()
                        .filter(pt -> getKey(pt, loaiThongKe).equals(key))
                        .mapToDouble(PhieuTraHang::getTongTienHoanTra)
                        .sum();
                    double doanhThu = tongHD - tongPT;
                    model.addRow(new Object[]{key, dinhDangTien(tongHD), dinhDangTien(tongPT), dinhDangTien(doanhThu)});
                    tongDoanhThu += doanhThu;
                }

                lblTongDoanhThu.setText("Tổng doanh thu: " + dinhDangTien(tongDoanhThu));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Lỗi khi xem báo cáo: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
            return null;
        }

        @Override
        protected void done() {
            // Hide loading
            disposeLoadingDialog();
        }
    };

    worker.execute();
}

    // Định dạng tiền như TraHangGUI
    private String dinhDangTien(double thanhTien) {
        DecimalFormat formatter = new DecimalFormat("#,###");
        return formatter.format(thanhTien) + " VNĐ";
    }

    // Get key cho HoaDon hoặc PhieuTraHang
    private String getKey(HoaDon hd, String loaiThongKe) {
        LocalDate date = hd.getNgayLapHoaDon().toLocalDate();
        if ("Theo ngày".equals(loaiThongKe)) {
            return date.format(DateTimeFormatter.ofPattern("dd/MM/yyyy"));
        } else if ("Theo tháng".equals(loaiThongKe)) {
            return String.format("%02d/%d", date.getMonthValue(), date.getYear());
        } else if ("Theo quý".equals(loaiThongKe)) {
            int quy = (date.getMonthValue() - 1) / 3 + 1;
            return "Quý " + quy + " năm " + date.getYear();
        } else if ("Theo năm".equals(loaiThongKe)) {
            return "Năm " + date.getYear();
        }
        return "";
    }

    private String getKey(PhieuTraHang pt, String loaiThongKe) {
        LocalDate date = pt.getNgayLapPhieuTraHang().toLocalDate();
        if ("Theo ngày".equals(loaiThongKe)) {
            return date.format(DateTimeFormatter.ofPattern("dd/MM/yyyy"));
        } else if ("Theo tháng".equals(loaiThongKe)) {
            return String.format("%02d/%d", date.getMonthValue(), date.getYear());
        } else if ("Theo quý".equals(loaiThongKe)) {
            int quy = (date.getMonthValue() - 1) / 3 + 1;
            return "Quý " + quy + " năm " + date.getYear();
        } else if ("Theo năm".equals(loaiThongKe)) {
            return "Năm " + date.getYear();
        }
        return "";
    }

private JDialog loadingDialog;

private void showLoadingDialog() {
    loadingDialog = new JDialog(
        (java.awt.Frame) SwingUtilities.getWindowAncestor(this),
        "Đang tải", 
        false
    );
    loadingDialog.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);

    // Panel chứa label + progress bar
    JPanel panel = new JPanel(new BorderLayout(10, 10));
    JLabel label = new JLabel("Đang thống kê dữ liệu...", SwingConstants.CENTER);
    label.setFont(new Font("Arial", Font.BOLD, 14));
    panel.add(label, BorderLayout.NORTH);

    // Thanh loading
    JProgressBar progressBar = new JProgressBar();
    progressBar.setIndeterminate(true); // chạy qua lại
    panel.add(progressBar, BorderLayout.CENTER);

    loadingDialog.getContentPane().add(panel);
    loadingDialog.pack(); // tự động tính kích thước
    loadingDialog.setLocationRelativeTo(this);

    this.setEnabled(false);
    loadingDialog.setVisible(true);
}

private void disposeLoadingDialog() {
    if (loadingDialog != null) {
        loadingDialog.dispose();
        loadingDialog = null;
    }
    this.setEnabled(true);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
