/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package hethongnhathuocduocankhang.gui;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.*;
import javax.swing.table.JTableHeader;

/**
 *
 * @author trand
 */
public class BanHangPane extends javax.swing.JPanel {

    /**
     * Creates new form BanHangGUI
     */
    public BanHangPane() {
        initComponents(); 

        JTableHeader header = tblCTHD.getTableHeader();
        header.setPreferredSize(new Dimension(header.getWidth(), 30));
        header.setBorder(null);
        header.setBackground(new Color(245, 245, 245));
        header.setForeground(Color.BLACK);
        header.setFont(new Font("Segoe UI", Font.BOLD, 14));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pSouth = new javax.swing.JPanel();
        pLeftSouth = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        pRightSouth = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        pRightCenter = new javax.swing.JPanel();
        pThongTinKH = new javax.swing.JPanel();
        p1 = new javax.swing.JPanel();
        lblSdtKH = new javax.swing.JLabel();
        txtSdtKH = new javax.swing.JTextField();
        p2 = new javax.swing.JPanel();
        lblThongTinKH = new javax.swing.JLabel();
        p3 = new javax.swing.JPanel();
        lblMaKH = new javax.swing.JLabel();
        p4 = new javax.swing.JPanel();
        lblHoTen = new javax.swing.JLabel();
        p5 = new javax.swing.JPanel();
        lblDiemTichLuy = new javax.swing.JLabel();
        pThanhToan = new javax.swing.JPanel();
        p6 = new javax.swing.JPanel();
        lblHinhThucThanhToan = new javax.swing.JLabel();
        p7 = new javax.swing.JPanel();
        chbTienMat = new javax.swing.JCheckBox();
        chbChuyenKhoan = new javax.swing.JCheckBox();
        p8 = new javax.swing.JPanel();
        lblTongTien = new javax.swing.JLabel();
        p9 = new javax.swing.JPanel();
        lblTienKhachDua = new javax.swing.JLabel();
        txtTienKhachDua = new javax.swing.JTextField();
        p10 = new javax.swing.JPanel();
        btnGoiY1 = new javax.swing.JButton();
        btnGoiY2 = new javax.swing.JButton();
        btnGoiY3 = new javax.swing.JButton();
        btnGoiY4 = new javax.swing.JButton();
        btnGoiY5 = new javax.swing.JButton();
        btnGoiY6 = new javax.swing.JButton();
        p11 = new javax.swing.JPanel();
        lblTienThua = new javax.swing.JLabel();
        pLeftCenter = new javax.swing.JPanel();
        jScrollPane = new javax.swing.JScrollPane();
        tblCTHD = new javax.swing.JTable();
        pTimKiem = new javax.swing.JPanel();
        btnTimKiem = new javax.swing.JButton();
        txtTimKiem = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        pSouth.setBackground(new java.awt.Color(255, 255, 255));
        pSouth.setPreferredSize(new java.awt.Dimension(100, 60));
        pSouth.setLayout(new java.awt.BorderLayout());
        pSouth.setBorder(BorderFactory.createEmptyBorder(0, 10, 0, 10));

        pLeftSouth.setBackground(new java.awt.Color(245, 245, 245));
        pLeftSouth.setPreferredSize(new java.awt.Dimension(400, 100));
        pLeftSouth.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 15));

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Xóa");
        jButton1.setPreferredSize(new java.awt.Dimension(100, 35));
        pLeftSouth.add(jButton1);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Xóa trắng");
        jButton2.setPreferredSize(new java.awt.Dimension(100, 35));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        pLeftSouth.add(jButton2);

        pSouth.add(pLeftSouth, java.awt.BorderLayout.LINE_START);

        pRightSouth.setBackground(new java.awt.Color(245, 245, 245));
        pRightSouth.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 10, 15));

        jButton3.setBackground(new java.awt.Color(0, 203, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Thanh toán");
        jButton3.setPreferredSize(new java.awt.Dimension(110, 35));
        pRightSouth.add(jButton3);

        pSouth.add(pRightSouth, java.awt.BorderLayout.CENTER);

        add(pSouth, java.awt.BorderLayout.PAGE_END);

        pRightCenter.setBackground(new java.awt.Color(255, 255, 255));
        pRightCenter.setPreferredSize(new java.awt.Dimension(300, 100));
        pRightCenter.setLayout(new java.awt.BorderLayout(0, 10));

        pThongTinKH.setBackground(new java.awt.Color(245, 245, 245));
        pThongTinKH.setLayout(new javax.swing.BoxLayout(pThongTinKH, javax.swing.BoxLayout.Y_AXIS));

        p1.setBackground(new java.awt.Color(245, 245, 245));
        p1.setPreferredSize(new java.awt.Dimension(100, 30));
        p1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        lblSdtKH.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblSdtKH.setForeground(new java.awt.Color(0, 0, 0));
        lblSdtKH.setText("SĐT khách hàng:");
        p1.add(lblSdtKH);

        pThongTinKH.add(p1);

        txtSdtKH.setBackground(new java.awt.Color(255, 255, 255));
        txtSdtKH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSdtKH.setForeground(new java.awt.Color(51, 51, 51));
        txtSdtKH.setText("0XXXXXXXXX");
        txtSdtKH.setPreferredSize(new java.awt.Dimension(95, 30));
        txtSdtKH.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createLineBorder(Color.BLACK, 1, true),
            BorderFactory.createEmptyBorder(0, 10, 0, 0)
        ));
        pThongTinKH.add(txtSdtKH);

        p2.setBackground(new java.awt.Color(245, 245, 245));
        p2.setPreferredSize(new java.awt.Dimension(100, 30));
        p2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lblThongTinKH.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblThongTinKH.setForeground(new java.awt.Color(0, 0, 0));
        lblThongTinKH.setText("Thông tin khách hàng:");
        p2.add(lblThongTinKH);

        pThongTinKH.add(p2);

        p3.setBackground(new java.awt.Color(245, 245, 245));
        p3.setPreferredSize(new java.awt.Dimension(100, 30));
        p3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lblMaKH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMaKH.setForeground(new java.awt.Color(51, 51, 51));
        lblMaKH.setText("Mã khách hàng:");
        p3.add(lblMaKH);

        pThongTinKH.add(p3);

        p4.setBackground(new java.awt.Color(245, 245, 245));
        p4.setPreferredSize(new java.awt.Dimension(100, 30));
        p4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lblHoTen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblHoTen.setForeground(new java.awt.Color(51, 51, 51));
        lblHoTen.setText("Họ tên:");
        p4.add(lblHoTen);

        pThongTinKH.add(p4);

        p5.setBackground(new java.awt.Color(245, 245, 245));
        p5.setPreferredSize(new java.awt.Dimension(100, 30));
        p5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lblDiemTichLuy.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDiemTichLuy.setForeground(new java.awt.Color(51, 51, 51));
        lblDiemTichLuy.setText("Điểm tích lũy:");
        p5.add(lblDiemTichLuy);

        pThongTinKH.add(p5);

        pRightCenter.add(pThongTinKH, java.awt.BorderLayout.PAGE_START);

        pThanhToan.setBackground(new java.awt.Color(245, 245, 245));
        pThanhToan.setLayout(new javax.swing.BoxLayout(pThanhToan, javax.swing.BoxLayout.Y_AXIS));

        p6.setBackground(new java.awt.Color(245, 245, 245));
        p6.setPreferredSize(new java.awt.Dimension(100, 30));
        p6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lblHinhThucThanhToan.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblHinhThucThanhToan.setForeground(new java.awt.Color(0, 0, 0));
        lblHinhThucThanhToan.setText("Hình thức thanh toán:");
        p6.add(lblHinhThucThanhToan);

        p6.setPreferredSize(new Dimension(Short.MAX_VALUE, 30));
        p6.setMaximumSize(new Dimension(Integer.MAX_VALUE, 30));
        p6.setMinimumSize(new Dimension(0, 30));

        pThanhToan.add(p6);

        p7.setBackground(new java.awt.Color(245, 245, 245));
        p7.setPreferredSize(new java.awt.Dimension(100, 30));

        chbTienMat.setBackground(new java.awt.Color(245, 245, 245));
        chbTienMat.setForeground(new java.awt.Color(51, 51, 51));
        chbTienMat.setText("Tiền mặt");
        p7.add(chbTienMat);

        chbChuyenKhoan.setBackground(new java.awt.Color(245, 245, 245));
        chbChuyenKhoan.setForeground(new java.awt.Color(51, 51, 51));
        chbChuyenKhoan.setText("Chuyển khoản");
        p7.add(chbChuyenKhoan);

        p7.setPreferredSize(new Dimension(Short.MAX_VALUE, 30));
        p7.setMaximumSize(new Dimension(Integer.MAX_VALUE, 30));
        p7.setMinimumSize(new Dimension(0, 30));

        pThanhToan.add(p7);

        p8.setBackground(new java.awt.Color(245, 245, 245));
        p8.setPreferredSize(new java.awt.Dimension(100, 30));
        p8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lblTongTien.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblTongTien.setForeground(new java.awt.Color(0, 0, 0));
        lblTongTien.setText("Tổng tiền:");
        p8.add(lblTongTien);

        p8.setPreferredSize(new Dimension(Short.MAX_VALUE, 30));
        p8.setMaximumSize(new Dimension(Integer.MAX_VALUE, 30));
        p8.setMinimumSize(new Dimension(0, 30));

        pThanhToan.add(p8);

        p9.setBackground(new java.awt.Color(245, 245, 245));
        p9.setPreferredSize(new java.awt.Dimension(100, 30));
        p9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lblTienKhachDua.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblTienKhachDua.setForeground(new java.awt.Color(0, 0, 0));
        lblTienKhachDua.setText("Tiền khách đưa:");
        p9.add(lblTienKhachDua);

        p9.setPreferredSize(new Dimension(Short.MAX_VALUE, 30));
        p9.setMaximumSize(new Dimension(Integer.MAX_VALUE, 30));
        p9.setMinimumSize(new Dimension(0, 30));

        pThanhToan.add(p9);

        txtTienKhachDua.setBackground(new java.awt.Color(255, 255, 255));
        txtTienKhachDua.setPreferredSize(new java.awt.Dimension(64, 30));
        txtTienKhachDua.setPreferredSize(new Dimension(Short.MAX_VALUE, 30));
        txtTienKhachDua.setMaximumSize(new Dimension(Integer.MAX_VALUE, 30));
        txtTienKhachDua.setMinimumSize(new Dimension(0, 30));
        pThanhToan.add(txtTienKhachDua);

        p10.setBackground(new java.awt.Color(245, 245, 245));
        p10.setPreferredSize(new java.awt.Dimension(100, 80));
        p10.setLayout(new java.awt.GridLayout(2, 3, 5, 5));

        btnGoiY1.setText("100");
        p10.add(btnGoiY1);

        btnGoiY2.setText("200");
        p10.add(btnGoiY2);

        btnGoiY3.setText("300");
        p10.add(btnGoiY3);

        btnGoiY4.setText("400");
        p10.add(btnGoiY4);

        btnGoiY5.setText("500");
        p10.add(btnGoiY5);

        btnGoiY6.setText("600");
        p10.add(btnGoiY6);

        p10.setPreferredSize(new Dimension(Short.MAX_VALUE, 60));
        p10.setMaximumSize(new Dimension(Integer.MAX_VALUE, 60));
        p10.setMinimumSize(new Dimension(0, 60));
        pThanhToan.add(Box.createVerticalStrut(5));

        pThanhToan.add(p10);

        p11.setBackground(new java.awt.Color(245, 245, 245));
        p11.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lblTienThua.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblTienThua.setForeground(new java.awt.Color(0, 0, 0));
        lblTienThua.setText("Tiền thừa:");
        p11.add(lblTienThua);

        pThanhToan.add(p11);

        pRightCenter.add(pThanhToan, java.awt.BorderLayout.CENTER);

        pRightCenter.setBorder(BorderFactory.createEmptyBorder(0, 10, 10, 10));

        add(pRightCenter, java.awt.BorderLayout.LINE_END);

        pLeftCenter.setBackground(new java.awt.Color(255, 255, 255));
        pLeftCenter.setLayout(new java.awt.BorderLayout(0, 10));

        jScrollPane.setBorder(BorderFactory.createEmptyBorder());
        jScrollPane.setBackground(new java.awt.Color(255, 255, 255));

        tblCTHD.setBackground(new java.awt.Color(245, 245, 245));
        tblCTHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tên sản phẩm", "Đơn vị tính", "Số lượng", "Thành tiền"
            }
        ));
        tblCTHD.setRowHeight(50);
        tblCTHD.setShowHorizontalLines(true);
        tblCTHD.setShowVerticalLines(false);
        tblCTHD.setGridColor(new Color(220, 220, 220));
        tblCTHD.setIntercellSpacing(new Dimension(0, 0));
        jScrollPane.setViewportView(tblCTHD);
        if (tblCTHD.getColumnModel().getColumnCount() > 0) {
            tblCTHD.getColumnModel().getColumn(0).setPreferredWidth(200);
        }

        pLeftCenter.add(jScrollPane, java.awt.BorderLayout.CENTER);

        pTimKiem.setBackground(new java.awt.Color(255, 255, 255));
        pTimKiem.setPreferredSize(new java.awt.Dimension(100, 40));
        pTimKiem.setLayout(new java.awt.BorderLayout(0, 10));
        pTimKiem.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));

        btnTimKiem.setBackground(new java.awt.Color(255, 255, 255));
        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/search.png"))); // NOI18N
        btnTimKiem.setPreferredSize(new java.awt.Dimension(38, 40));
        btnTimKiem.setBorder(BorderFactory.createLineBorder(Color.BLACK, 1));
        btnTimKiem.setCursor(new Cursor(Cursor.HAND_CURSOR));
        pTimKiem.add(btnTimKiem, java.awt.BorderLayout.LINE_END);

        txtTimKiem.setBackground(new java.awt.Color(255, 255, 255));
        txtTimKiem.setForeground(new java.awt.Color(117, 117, 117));
        txtTimKiem.setText("Nhập mã sản phẩm");
        txtTimKiem.setPreferredSize(new java.awt.Dimension(119, 40));
        txtTimKiem.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createLineBorder(Color.BLACK, 1, true),
            BorderFactory.createEmptyBorder(0, 10, 0, 0)
        ));
        pTimKiem.add(txtTimKiem, java.awt.BorderLayout.CENTER);

        pLeftCenter.add(pTimKiem, java.awt.BorderLayout.PAGE_START);

        pLeftCenter.setBorder(BorderFactory.createEmptyBorder(5, 10, 10, 0));

        add(pLeftCenter, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGoiY1;
    private javax.swing.JButton btnGoiY2;
    private javax.swing.JButton btnGoiY3;
    private javax.swing.JButton btnGoiY4;
    private javax.swing.JButton btnGoiY5;
    private javax.swing.JButton btnGoiY6;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JCheckBox chbChuyenKhoan;
    private javax.swing.JCheckBox chbTienMat;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JLabel lblDiemTichLuy;
    private javax.swing.JLabel lblHinhThucThanhToan;
    private javax.swing.JLabel lblHoTen;
    private javax.swing.JLabel lblMaKH;
    private javax.swing.JLabel lblSdtKH;
    private javax.swing.JLabel lblThongTinKH;
    private javax.swing.JLabel lblTienKhachDua;
    private javax.swing.JLabel lblTienThua;
    private javax.swing.JLabel lblTongTien;
    private javax.swing.JPanel p1;
    private javax.swing.JPanel p10;
    private javax.swing.JPanel p11;
    private javax.swing.JPanel p2;
    private javax.swing.JPanel p3;
    private javax.swing.JPanel p4;
    private javax.swing.JPanel p5;
    private javax.swing.JPanel p6;
    private javax.swing.JPanel p7;
    private javax.swing.JPanel p8;
    private javax.swing.JPanel p9;
    private javax.swing.JPanel pLeftCenter;
    private javax.swing.JPanel pLeftSouth;
    private javax.swing.JPanel pRightCenter;
    private javax.swing.JPanel pRightSouth;
    private javax.swing.JPanel pSouth;
    private javax.swing.JPanel pThanhToan;
    private javax.swing.JPanel pThongTinKH;
    private javax.swing.JPanel pTimKiem;
    private javax.swing.JTable tblCTHD;
    private javax.swing.JTextField txtSdtKH;
    private javax.swing.JTextField txtTienKhachDua;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
