/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hethongnhathuocduocankhang.gui;

import hethongnhathuocduocankhang.connectDB.ConnectDB;
import hethongnhathuocduocankhang.dao.TaiKhoanDAO;
import hethongnhathuocduocankhang.entity.TaiKhoan;
import java.awt.Cursor;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.net.URL;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author trand
 */
public class DangNhapGUI extends javax.swing.JFrame{
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DangNhapGUI.class.getName());
    private static boolean isVisible = false;
    /**
     * Creates new form DangNhapGUI
     */
    public DangNhapGUI() {
        initComponents();

        try {
            ConnectDB.getInstance().connect();
        }catch(SQLException e) {
            e.printStackTrace();
        }
        
        URL url = DangNhapGUI.class.getResource("/resources/images/logo.png");
        Image icon = Toolkit.getDefaultToolkit().createImage(url);
        this.setIconImage(icon);
        
        lblQuenMatKhau.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnCheMatKhau.setCursor(new Cursor(Cursor.HAND_CURSOR));
        txtTaiKhoan.setBorder(new EmptyBorder(5, 10, 5, 10));
        txtMatKhau.setBorder(new EmptyBorder(5, 10, 5, 10));
        txtMatKhau.setEchoChar('•');
        btnCheMatKhau.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                cheMatKhau();
            }
        });
        setTitle("Đăng nhập");
        setSize(850, 600);
        setResizable(false);
        setLocationRelativeTo(null);
        setVisible(true);
        
        // Mặc định để đỡ phải đăng nhập mỗi lần test
        txtTaiKhoan.setText("NV-0001");
        txtMatKhau.setText("VoTienKhoa123@");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pCenter = new javax.swing.JPanel();
        pDangNhap = new javax.swing.JPanel();
        lblTitle1 = new javax.swing.JLabel();
        lblTitle2 = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        lblTaiKhoan = new javax.swing.JLabel();
        txtTaiKhoan = new javax.swing.JTextField();
        lblMatKhau = new javax.swing.JLabel();
        btnDangNhap = new javax.swing.JButton();
        lblQuenMatKhau = new javax.swing.JLabel();
        txtMatKhau = new javax.swing.JPasswordField();
        btnCheMatKhau = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pCenter.setBackground(new java.awt.Color(25, 118, 210));
        pCenter.setLayout(new java.awt.GridBagLayout());

        pDangNhap.setBackground(new java.awt.Color(255, 255, 255));
        pDangNhap.setPreferredSize(new java.awt.Dimension(450, 350));
        pDangNhap.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblTitle1.setForeground(new java.awt.Color(25, 118, 210));
        lblTitle1.setText("NHÀ THUỐC");
        pDangNhap.add(lblTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        lblTitle2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblTitle2.setForeground(new java.awt.Color(25, 118, 210));
        lblTitle2.setText("DƯỢC AN KHANG");
        pDangNhap.add(lblTitle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, -1, -1));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/logo.png"))); // NOI18N
        pDangNhap.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        lblTaiKhoan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTaiKhoan.setForeground(new java.awt.Color(25, 118, 210));
        lblTaiKhoan.setText("Tài khoản:");
        pDangNhap.add(lblTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        txtTaiKhoan.setBackground(new java.awt.Color(245, 245, 245));
        txtTaiKhoan.setBorder(null);
        pDangNhap.add(txtTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 330, 40));

        lblMatKhau.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMatKhau.setForeground(new java.awt.Color(25, 118, 210));
        lblMatKhau.setText("Mật khẩu:");
        pDangNhap.add(lblMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        btnDangNhap.setBackground(new java.awt.Color(25, 118, 210));
        btnDangNhap.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDangNhap.setForeground(new java.awt.Color(255, 255, 255));
        btnDangNhap.setText("Đăng nhập");
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });
        pDangNhap.add(btnDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 330, 40));

        lblQuenMatKhau.setBackground(new java.awt.Color(51, 51, 51));
        lblQuenMatKhau.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblQuenMatKhau.setText("<html><u>Quên mật khẩu?</u></html>");
        lblQuenMatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQuenMatKhauMouseClicked(evt);
            }
        });
        pDangNhap.add(lblQuenMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 90, 30));

        txtMatKhau.setBackground(new java.awt.Color(245, 245, 245));
        txtMatKhau.setBorder(null);
        txtMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatKhauActionPerformed(evt);
            }
        });
        pDangNhap.add(txtMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 290, 40));

        btnCheMatKhau.setBackground(new java.awt.Color(245, 245, 245));
        btnCheMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/hidePasswordEye.png"))); // NOI18N
        btnCheMatKhau.setToolTipText("");
        btnCheMatKhau.setBorder(null);
        pDangNhap.add(btnCheMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 40, 40));

        pCenter.add(pDangNhap, new java.awt.GridBagConstraints());

        getContentPane().add(pCenter, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        dangNhap();
    }//GEN-LAST:event_btnDangNhapActionPerformed

    private void dangNhap() {
        String tenDangNhap = txtTaiKhoan.getText().trim();
        String matKhau = new String(txtMatKhau.getPassword()).trim();

        if (tenDangNhap.isEmpty() || matKhau.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Vui lòng nhập đầy đủ tài khoản và mật khẩu!",
                    "Thiếu thông tin",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        TaiKhoan tk = TaiKhoanDAO.getTaiKhoanTheoTenDangNhapVaMatKhau(tenDangNhap, matKhau);
        if (tk != null) {          
            new GiaoDienChinhGUI(tk);
            this.dispose();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Sai tài khoản hoặc mật khẩu!",
                    "Đăng nhập thất bại",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void txtMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatKhauActionPerformed
        dangNhap();
    }//GEN-LAST:event_txtMatKhauActionPerformed

    private void lblQuenMatKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuenMatKhauMouseClicked
        String email = JOptionPane.showInputDialog(this, "Nhập email đã đăng ký để đặt lại mật khẩu:");
        if (email != null && !email.trim().isEmpty()) {
            if (TaiKhoanDAO.kiemTraEmailTonTai(email.trim())) {
                JOptionPane.showMessageDialog(this,
                    "Một liên kết đặt lại mật khẩu đã được gửi đến " + email,
                    "Đặt lại mật khẩu",
                    JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this,
                    "Email không tồn tại trong hệ thống!",
                    "Lỗi",
                    JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_lblQuenMatKhauMouseClicked

    private void cheMatKhau() {
        isVisible = !isVisible;
        if (isVisible) {
            txtMatKhau.setEchoChar((char) 0);
        } else {
            txtMatKhau.setEchoChar('•');
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DangNhapGUI().setVisible(true));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheMatKhau;
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMatKhau;
    private javax.swing.JLabel lblQuenMatKhau;
    private javax.swing.JLabel lblTaiKhoan;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblTitle2;
    private javax.swing.JPanel pCenter;
    private javax.swing.JPanel pDangNhap;
    private javax.swing.JPasswordField txtMatKhau;
    private javax.swing.JTextField txtTaiKhoan;
    // End of variables declaration//GEN-END:variables
}
