/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hethongnhathuocduocankhang.gui;

import hethongnhathuocduocankhang.menu.MenuEvent;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author trand
 */
public class GiaoDienChinhGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GiaoDienChinhGUI.class.getName());

    /**
     * Creates new form GiaoDienChinhGUI
     */
    public GiaoDienChinhGUI() {
        initComponents();
        menu.setEvent(new MenuEvent() {
            @Override
            public void selected(int index, int subIndex) {
                if(index == 0 && subIndex == 0) {
                    showPanel(new TongQuanGUI());
                }
                if(index == 1 && subIndex == 0) {
                    showPanel(new BanHangGUI());
                }
                if(index == 2) {
                        switch (subIndex) {
                            case 1:
                                showPanel(new QuanLiKhachHangGUI());
                                break;
                            case 2:
                                showPanel(new QuanLiSanPhamGUI());
                                break;
                            case 3:
                                showPanel(new QuanLiNhanVienGUI());
                                break;
                            case 4:
                                showPanel(new QuanLiHoaDonGUI());
                                break;
                            case 5:
                                showPanel(new QuanLiKhuyenMaiGUI());
                                break;
                            case 6:
                                showPanel(new QuanLiNhaCungCapGUI());
                                break;
                            case 7:
                                showPanel(new QuanLiPhieuDatHangGUI());
                                break;
                            case 8:
                                showPanel(new QuanLiLichSuCaLamGUI());
                                break;
                            case 9:
                                showPanel(new QuanLiPhieuTraHangGUI());
                                break;
                            default:    
                        }
                } 
                if(index == 3 && subIndex == 0) {
                    showPanel(new TraHangGUI());
                } 
                if(index == 4 && subIndex == 0) {
                    showPanel(new TaoPhieuDatHangGUI());
                } 
                if(index == 8 && subIndex == 0) {
                    dangXuat();
                }
            }
        });
        setTitle("Hệ thống nhà thuốc Dược An Khang");
        setSize(1000, 600);
        setLocationRelativeTo(null);
        setVisible(true);
    }
    
    private void dangXuat() {
        int confirm = JOptionPane.showConfirmDialog(this,
                        "Bạn có chắc chắn muốn đăng xuất không?",
                        "Xác nhận đăng xuất",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE);
        if (confirm == JOptionPane.YES_OPTION) {
            this.dispose();
            new DangNhapGUI();
        }
}

    
    
    private void showPanel(JPanel p) {
        pCenter.removeAll();
        p.setSize(pCenter.getSize());
        p.setVisible(true);
        pCenter.setLayout(new java.awt.BorderLayout());
        pCenter.add(p, java.awt.BorderLayout.CENTER);
        pCenter.revalidate();
        pCenter.repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pLeft = new javax.swing.JPanel();
        pLogo = new javax.swing.JPanel();
        scrollPaneWin11 = new hethongnhathuocduocankhang.scroll.win11.ScrollPaneWin11();
        menu = new hethongnhathuocduocankhang.menu.Menu();
        pCenter = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1000, 600));

        pLeft.setBackground(new java.awt.Color(25, 118, 210));
        pLeft.setPreferredSize(new java.awt.Dimension(200, 558));
        pLeft.setLayout(new java.awt.BorderLayout());

        pLogo.setBackground(new java.awt.Color(25, 118, 210));
        pLogo.setPreferredSize(new java.awt.Dimension(200, 120));

        javax.swing.GroupLayout pLogoLayout = new javax.swing.GroupLayout(pLogo);
        pLogo.setLayout(pLogoLayout);
        pLogoLayout.setHorizontalGroup(
            pLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        pLogoLayout.setVerticalGroup(
            pLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        pLeft.add(pLogo, java.awt.BorderLayout.PAGE_START);

        menu.setBackground(new java.awt.Color(25, 118, 210));
        menu.setPreferredSize(new java.awt.Dimension(200, 328));
        scrollPaneWin11.setViewportView(menu);

        pLeft.add(scrollPaneWin11, java.awt.BorderLayout.CENTER);

        getContentPane().add(pLeft, java.awt.BorderLayout.LINE_START);

        pCenter.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pCenterLayout = new javax.swing.GroupLayout(pCenter);
        pCenter.setLayout(pCenterLayout);
        pCenterLayout.setHorizontalGroup(
            pCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 529, Short.MAX_VALUE)
        );
        pCenterLayout.setVerticalGroup(
            pCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 573, Short.MAX_VALUE)
        );

        getContentPane().add(pCenter, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new GiaoDienChinhGUI().setVisible(true));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private hethongnhathuocduocankhang.menu.Menu menu;
    private javax.swing.JPanel pCenter;
    private javax.swing.JPanel pLeft;
    private javax.swing.JPanel pLogo;
    private hethongnhathuocduocankhang.scroll.win11.ScrollPaneWin11 scrollPaneWin11;
    // End of variables declaration//GEN-END:variables
}
