/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package hethongnhathuocduocankhang.gui;
import java.util.ArrayList;

import hethongnhathuocduocankhang.bus.PhieuDatHangBUS;
import hethongnhathuocduocankhang.entity.DonViTinh;
import hethongnhathuocduocankhang.entity.NhaCungCap;
import hethongnhathuocduocankhang.entity.SanPham;
import hethongnhathuocduocankhang.entity.TaiKhoan;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.event.FocusEvent;
import javax.swing.DefaultCellEditor;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.event.DocumentEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableCellRenderer;
import javax.swing.text.AbstractDocument;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;
import javax.swing.text.PlainDocument;
import java.text.DecimalFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;


/**
 *
 * @author trand
 */
public class TaoPhieuDatHangGUI extends javax.swing.JPanel {
    private PhieuDatHangBUS phieuDatBUS;
    private String txtKhuyenMai = "Hello";
    /**
     * Creates new form TaoPhieuDatHangGUI
     */
    public TaoPhieuDatHangGUI() {
        initComponents();
        
        phieuDatBUS = new PhieuDatHangBUS();
        getSanPham();
        
        tblSanPham.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblSanPham.getColumnModel().getColumn(0).setPreferredWidth(80);  
        tblSanPham.getColumnModel().getColumn(1).setPreferredWidth(1080); 
        tblSanPham.getColumnModel().getColumn(2).setPreferredWidth(110); 
        tblSanPham.getColumn("Chọn").setCellRenderer(new btnThemSanPham());
        tblSanPham.getColumn("Chọn").setCellEditor(new btnThemChinh(new JCheckBox()));
        
        tblPhieuDat.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblPhieuDat.getColumnModel().getColumn(0).setPreferredWidth(80);
        tblPhieuDat.getColumnModel().getColumn(1).setPreferredWidth(368);
        tblPhieuDat.getColumnModel().getColumn(2).setPreferredWidth(100);
        tblPhieuDat.getColumnModel().getColumn(3).setPreferredWidth(120);
        tblPhieuDat.getColumnModel().getColumn(4).setPreferredWidth(100);
        tblPhieuDat.getColumnModel().getColumn(5).setPreferredWidth(100);
        tblPhieuDat.getColumn("Xóa").setCellRenderer(new btnXoa());
        tblPhieuDat.getColumn("Xóa").setCellEditor(new btnXoaChinh(new JCheckBox()));
        tblPhieuDat.getColumnModel().getColumn(3).setCellRenderer(new btnTangGiam());
        tblPhieuDat.getColumnModel().getColumn(3).setCellEditor(new btnSoLuong());
        
        thongTinPhieuDat();
        txtTimSanPham.addFocusListener(new java.awt.event.FocusAdapter(){
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                if(txtTimSanPham.getText().equals("Tìm kiếm sản phẩm...")){
                    txtTimSanPham.setText("");
                }
            }
            
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField5 = new javax.swing.JTextField();
        txtTenNhanVien = new javax.swing.JTextField();
        ngayLap = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblPhieuDat = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtTimSanPham = new javax.swing.JTextField();
        btnTimSanPham = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSanPham = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        btnXoaBang = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Thông tin phiếu đặt");

        jLabel2.setText("Mã phiếu đặt:");

        jLabel3.setText("Nhân viên:");

        jLabel4.setText("Ngày lập:");

        jLabel5.setText("Ghi chú:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jTextField5.setEnabled(false);
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        txtTenNhanVien.setEnabled(false);
        txtTenNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenNhanVienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(24, 24, 24)
                        .addComponent(txtTenNhanVien))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField5)
                            .addComponent(ngayLap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(ngayLap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.BorderLayout());
        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel6.setLayout(new java.awt.BorderLayout());

        tblPhieuDat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Nhà cung cấp", "Số lượng", "Đơn giá", "Thành tiền", "Xóa"
            }
        ));
        jScrollPane3.setViewportView(tblPhieuDat);

        jPanel6.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel6, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Mặt hàng");

        txtTimSanPham.setText("Tìm kiếm sản phẩm...");
        txtTimSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimSanPhamActionPerformed(evt);
            }
        });

        btnTimSanPham.setText("Tìm");
        btnTimSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimSanPhamActionPerformed(evt);
            }
        });

        jButton1.setText("R");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tblSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Chọn"
            }
        ));
        jScrollPane1.setViewportView(tblSanPham);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1042, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtTimSanPham)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTimSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setText("Tiền hàng:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel10.setText("Tổng tiền:");

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField4)))
                .addContainerGap(264, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        jButton4.setText("Xem trước");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("In phiếu");
        jButton5.setPreferredSize(new java.awt.Dimension(85, 23));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Làm mới");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Lưu");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        btnXoaBang.setText("Xóa bảng");
        btnXoaBang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaBangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(222, 222, 222)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnXoaBang, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnXoaBang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel9, java.awt.BorderLayout.CENTER);

        add(jPanel5, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void txtTimSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimSanPhamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimSanPhamActionPerformed

    private void btnTimSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimSanPhamActionPerformed
        // TODO add your handling code here:
       String maSanPham = txtTimSanPham.getText().trim().toUpperCase();
       if(maSanPham.isEmpty()){
           JOptionPane.showMessageDialog(this, "Chưa nhập mã sản phẩm!");
           txtTimSanPham.requestFocus();
           return;
       }
       if(!maSanPham.matches("SP-\\d{4}")){
           JOptionPane.showMessageDialog(this, "Mã sản phẩm phải đúng định dạng SP-0001");
           txtTimSanPham.setText("");
           txtTimSanPham.requestFocus();
           return;
       }
       SanPham s = phieuDatBUS.timSanPham(maSanPham);
       DefaultTableModel m = (DefaultTableModel) tblSanPham.getModel();
       m.setRowCount(0);
       if(s!=null)
            m.addRow(new Object[]{s.getMaSP(), s.getTen()});
       else{
           JOptionPane.showMessageDialog(this, "Mã sản phẩm không tồn tại!");
           getSanPham();
           txtTimSanPham.setText("");
           txtTimSanPham.requestFocus();
       }
    }//GEN-LAST:event_btnTimSanPhamActionPerformed
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        txtTimSanPham.setText("");
        txtTimSanPham.requestFocus();
        getSanPham(); 
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void txtTenNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenNhanVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenNhanVienActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        xemTruocPhieuTheoNCC();
            // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void btnXoaBangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaBangActionPerformed
        // TODO add your handling code here:
        int conf = JOptionPane.showConfirmDialog(this, "Xác nhận xóa tất cả sản phẩm trong bảng?", "Xác nhận?", JOptionPane.YES_NO_OPTION);
        if(conf==JOptionPane.YES_OPTION){
            DefaultTableModel mo = (DefaultTableModel) tblPhieuDat.getModel();
            mo.setRowCount(0);
        }
    }//GEN-LAST:event_btnXoaBangActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTimSanPham;
    private javax.swing.JButton btnXoaBang;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private com.toedter.calendar.JDateChooser ngayLap;
    private javax.swing.JTable tblPhieuDat;
    private javax.swing.JTable tblSanPham;
    private javax.swing.JTextField txtTenNhanVien;
    private javax.swing.JTextField txtTimSanPham;
    // End of variables declaration//GEN-END:variables
    
    TaiKhoan tk = GiaoDienChinhGUI.getTk();

    private void getSanPham() {
        ArrayList<SanPham> dsSP = phieuDatBUS.danhsachSanPham();
        DefaultTableModel m = (DefaultTableModel) tblSanPham.getModel();
        m.setRowCount(0);
        for(SanPham sp : dsSP){
            m.addRow(new Object[]{sp.getMaSP(), sp.getTen()});
        }
    }

    private void thongTinPhieuDat() {
        txtTenNhanVien.setText(tk.getNhanVien().getHoTenDem() + " " + tk.getNhanVien().getTen());
        ngayLap.setDate(new Date());
    }

    class btnSoLuong extends DefaultCellEditor{
        private JButton btnTang;
        private JButton btnGiam;
        private JPanel p;
        private javax.swing.JTextField txtSL;
        int row;
        public btnSoLuong() {
            super(new JCheckBox());
            
            p = new JPanel();
            p.setLayout(new java.awt.BorderLayout());
            btnTang = new JButton("+");
            btnGiam = new JButton("-");
            txtSL = new javax.swing.JTextField("1");
            txtSL.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            txtSL.getDocument().addDocumentListener(new javax.swing.event.DocumentListener(){
                @Override
                public void insertUpdate(DocumentEvent e) {
                    capNhatGiaKhiNhap();
                }

                @Override
                public void removeUpdate(DocumentEvent e) {
                    capNhatGiaKhiNhap();
                }

                @Override
                public void changedUpdate(DocumentEvent e) {
                    capNhatGiaKhiNhap();
                }

                private void capNhatGiaKhiNhap() {
                    try {
                        int v = Integer.parseInt(txtSL.getText().trim());
                        if(v>0){
                            updateGiaTri(v);
                        }
                    } catch (Exception exception) {
                    }
                }
            });            
            btnGiam.addActionListener(e->{
                int value = Integer.parseInt(txtSL.getText());
                if(value>1){
                    value--;
                    txtSL.setText(String.valueOf(value));
                    tblPhieuDat.setValueAt(value, row, 3);
                    updateGiaTri(value);
                }
            });
            btnTang.addActionListener(e->{
                int value = Integer.parseInt(txtSL.getText());
                value++;
                txtSL.setText(String.valueOf(value));
                tblPhieuDat.setValueAt(value, row, 3);
                updateGiaTri(value);
            });
            
            p.add(btnGiam, java.awt.BorderLayout.WEST);
            p.add(txtSL, java.awt.BorderLayout.CENTER);
            p.add(btnTang, java.awt.BorderLayout.EAST);
            
            txtSL.addFocusListener(new java.awt.event.FocusAdapter() {
                @Override
                public void focusLost(FocusEvent e) {
                    try {
                        int v = Integer.parseInt(txtSL.getText().trim());
                        updateGiaTri(v);
                    } catch (Exception exception) {
                    }
                }
                
            });
        }
        
        
        public void updateGiaTri(int x){
            if (tblPhieuDat.isEditing()) {
                tblPhieuDat.getCellEditor().stopCellEditing();
            }
            if(row<0 || row >= tblPhieuDat.getRowCount()) return;
            
            txtSL.setText(String.valueOf(x));
            DefaultTableModel m = (DefaultTableModel) tblPhieuDat.getModel();
            m.setValueAt(x, row, 3);
            
            try {
                String giaText = m.getValueAt(row, 4).toString().replace("VND", "").replace(",", "").trim();
                double donGia = Double.parseDouble(giaText);
                double thanhTien = donGia * x;
                DecimalFormat df = new DecimalFormat("#,##0.000");
                m.setValueAt(df.format(thanhTien * 1000)+"VND", row, 5);
            } catch (Exception exception) {
            }
            tblPhieuDat.repaint();
            tblPhieuDat.revalidate();
        }
        
        @Override
        public Component getTableCellEditorComponent(JTable table, Object value, boolean isSelected, int row, int column) {
            this.row=row;
            if(value != null) txtSL.setText(value.toString());
            return p;
        }

        @Override
        public Object getCellEditorValue() {
            return txtSL.getText();
        }
        
        
    }

    class btnTangGiam extends JPanel implements TableCellRenderer{
        JButton btnTang = new JButton("+");
        JButton btnGiam = new JButton("-");
        JTextField txtSL = new JTextField();
        
        public btnTangGiam(){
            setLayout(new BorderLayout());
            add(btnTang, BorderLayout.EAST);
            add(btnGiam, BorderLayout.WEST);
            add(txtSL, BorderLayout.CENTER);
            txtSL.setHorizontalAlignment(JTextField.CENTER);
            txtSL.setEditable(false);
        }

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            txtSL.setText(value.toString());
            if (isSelected) setBackground(table.getSelectionBackground());
            else setBackground(table.getBackground());
            return this;
        }
        
    }
    
    class btnXoa extends JButton implements TableCellRenderer {
        public btnXoa() {
            setText("Xóa");
        }
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            return this;
        }
        
    }

    class btnXoaChinh extends DefaultCellEditor{
        private JButton btn;
        private int row;
        private boolean click;
        public btnXoaChinh(JCheckBox ck) {
            super(ck);
            btn = new JButton("Xóa");
            btn.addActionListener(e->{
                if(tblPhieuDat.isEditing()) tblPhieuDat.getCellEditor().stopCellEditing();
                int conf = JOptionPane.showConfirmDialog(null, "Xóa sản phẩm ?", "Xác nhận?", JOptionPane.YES_NO_OPTION);
                if(conf == JOptionPane.YES_OPTION){
                    if(row>=0 && row<tblPhieuDat.getRowCount()){
                        DefaultTableModel m = (DefaultTableModel) tblPhieuDat.getModel();
                        m.removeRow(row);
                    }
                }
            });
        }

        @Override
        public Component getTableCellEditorComponent(JTable table, Object value, boolean isSelected, int row, int column) {
            this.row = row;
            btn.setText("Xóa");
            click = true;
            return btn;
        }

        @Override
        public Object getCellEditorValue() {
            click = false;
            return null;
        }
    }

    class btnThemChinh extends DefaultCellEditor  {
        private JButton btn;
        private boolean click;
        private int row;
        
        public btnThemChinh(JCheckBox btnThem) {
            super(new JCheckBox());
            btn = new JButton("Thêm");
            btn.addActionListener(e->fireEditingStopped());
            
        }

        @Override
        public Component getTableCellEditorComponent(JTable table, Object value, boolean isSelected, int row, int column) {
            this.row = row;
            btn.setText("Thêm");
            click = true;
            return btn;
        }

        @Override
        public Object getCellEditorValue() {
            if(click){
                String maSP = tblSanPham.getValueAt(row, 0).toString();
                loadTable(maSP);
            }click=false;
            return null;
        }
        
    }

    class btnThemSanPham extends JButton implements TableCellRenderer {

        public btnThemSanPham() {
            setText("Thêm");
        }

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            return this;
        }
        
    }
    

    
    public void loadTable(String ma){
        SanPham sp = phieuDatBUS.timSanPham(ma);
        NhaCungCap ncc = phieuDatBUS.timNhaCC(ma);
        DonViTinh dvt = phieuDatBUS.giaSanPham(ma);
        if(ncc==null){
            JOptionPane.showMessageDialog(this, "Nhà cung cấp rỗng!");
            return;
        }
        if(dvt==null){
            JOptionPane.showMessageDialog(this, "Đơn vị tính không tồn tại!");
            return;
        }
        DefaultTableModel tbl = (DefaultTableModel) tblPhieuDat.getModel();
        int soLuong =1;
        double donGia = dvt.getGiaBanTheoDonVi();
        for (int i = 0; i < tbl.getRowCount(); i++) {
            String maMoi = tbl.getValueAt(i, 0).toString();
            if(maMoi.equals(ma)){
                int sl = Integer.parseInt(tbl.getValueAt(i, 3).toString());
                sl++;
                tbl.setValueAt(sl, i, 3);
                
                double thanhTien = sl*donGia;
                DecimalFormat df = new DecimalFormat("#,##0.000");
                tbl.setValueAt(df.format(thanhTien)+"VND", i, 5);
                tblPhieuDat.revalidate();
                tblPhieuDat.repaint();
                return;
            }
        }
        
        
        double thanhTien = phieuDatBUS.tinh(soLuong, dvt);
        DecimalFormat df = new DecimalFormat("#,##0.000");
        String donGiaText = df.format(donGia) + "VND";
        String thanhTienText = df.format(thanhTien) + "VND";
        
        tbl.addRow(new Object[]{sp.getMaSP(), sp.getTen(), ncc.getMaNCC(), soLuong, donGiaText,thanhTienText, "Xóa"}); 

        tblPhieuDat.revalidate();
        tblPhieuDat.repaint();
    }
    
    
        private void xemTruocPhieuTheoNCC() {
            DefaultTableModel model = (DefaultTableModel) tblPhieuDat.getModel();
            if(model.getRowCount() == 0){
                JOptionPane.showMessageDialog(this, "Bảng phiếu đang trống!", "Thông báo", JOptionPane.WARNING_MESSAGE);
                return;
            }
            Map<String, List<Integer>> nccMap = new HashMap<>();
            for (int i=0;i<model.getRowCount();i++){
                String ncc = model.getValueAt(i,2).toString();
                nccMap.computeIfAbsent(ncc, k -> new ArrayList<>()).add(i);
            }
            for(String ncc : nccMap.keySet()){
                StringBuilder sb = new StringBuilder();
                sb.append("PHIẾU ĐẶT HÀNG - NCC:   ").append(ncc).append("\n");
                sb.append("Mã phiếu: ").append(jTextField5.getText())
                  .append("\tNgày lập: ").append(ngayLap.getDate()).append("\n");
                sb.append("Nhân viên: ").append(txtTenNhanVien.getText()).append("\n");
                sb.append("Ghi chú: ").append(jTextArea1.getText()).append("\n");
                sb.append("-----------------------------------------------------------------------------------------------------------\n");

                sb.append(String.format("%-5s%-10s%-25s%-10s%20s%18s%18s\n",
                        "STT","Mã SP","Tên SP","NCC","SL","Đơn giá","Thành tiền"));
                List<Integer> rows = nccMap.get(ncc);
                for(int i=0;i<rows.size();i++){
                    int row = rows.get(i);
                    sb.append(String.format("%-5s%-10s%-25s%-10s%20s%18s%18s\n",
                            (i+1),
                            model.getValueAt(row,0),
                            formatText(model.getValueAt(row,1).toString(),25),
                            model.getValueAt(row,2),
                            model.getValueAt(row,3),
                            model.getValueAt(row,4),
                            model.getValueAt(row,5)
                    ));
                }

                sb.append("-----------------------------------------------------------------------------------------------------------\n");
                double tong = 0;
                for(int row : rows){
                    try{
                        String giaText = model.getValueAt(row,5).toString().replace("VND","").replace(",","");
                        tong += Double.parseDouble(giaText);
                    }catch(Exception e){}
                }
                sb.append("Tổng cộng NCC ").append(ncc).append(": ").append(String.format("%,.0f", tong*1000)).append(" VND\n");

                JTextArea textArea = new JTextArea(sb.toString());
                textArea.setEditable(false);
                textArea.setFont(new java.awt.Font("Monospaced", java.awt.Font.PLAIN, 12));
                JScrollPane scrollPane = new JScrollPane(textArea);
                JOptionPane.showMessageDialog(this, scrollPane, "Phiếu đặt - NCC: " + ncc, JOptionPane.INFORMATION_MESSAGE);
            }
        }

        private String formatText(String text, int length){
            if(text.length() > length){
                return text.substring(0,length-3) + "...";
            } else {
                return String.format("%-" + length + "s", text);
            }
        }

}
