/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package hethongnhathuocduocankhang.gui;

import com.microsoft.sqlserver.jdbc.SQLServerException;
import hethongnhathuocduocankhang.dao.ChiTietHoaDonDAO;
import hethongnhathuocduocankhang.dao.ChiTietPhieuTraDAO;
import hethongnhathuocduocankhang.dao.HoaDonDAO;
import hethongnhathuocduocankhang.dao.NhanVienDAO;
import hethongnhathuocduocankhang.dao.PhieuDatHangDAO;
import hethongnhathuocduocankhang.dao.PhieuTraHangDAO;
import hethongnhathuocduocankhang.entity.ChiTietHoaDon;
import hethongnhathuocduocankhang.entity.ChiTietPhieuTraHang;
import hethongnhathuocduocankhang.entity.HoaDon;
import hethongnhathuocduocankhang.entity.NhanVien;
import hethongnhathuocduocankhang.entity.PhieuTraHang;
import hethongnhathuocduocankhang.entity.TinhTrangSanPhamEnum;
import hethongnhathuocduocankhang.entity.TruongHopDoiTraEnum;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.KeyboardFocusManager;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.List;
import javax.swing.AbstractAction;
import javax.swing.AbstractButton;
import javax.swing.ActionMap;
import javax.swing.DefaultCellEditor;
import javax.swing.InputMap;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.KeyStroke;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableColumn;

/**
 *
 * @author trand
 */
public class TraHangGUI extends javax.swing.JPanel {

    private JLabel lblSoLanTra;
    private JLabel lblSoNgayHD;
    private JLabel lblTongTienTra;

    /**
     * Creates new form TraHangGUI
     */
    public TraHangGUI() {
        initComponents();
        initInfoPanels(); // Khởi tạo 3 ô thông tin

        mapKeyToFocus("F3", txtNhapMaHoaDon);
        mapKeyToClickButton("F7", btnChonTatCa);
        mapKeyToClickButton("F8", btnBoChonTatCa);
        mapKeyToClickButton("F4", btnXacNhan);

        mapKeyToClickButton("F9", btnXoaDong);
        mapKeyToClickButton("F10", btnXoaRong);
        mapKeyToClickButton("F6", btnTaoPhieu);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel24 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        txtNhapMaHoaDon = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jPanel30 = new javax.swing.JPanel();
        btnChonTatCa = new javax.swing.JButton();
        btnBoChonTatCa = new javax.swing.JButton();
        jPanel23 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnXacNhan = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCTHD = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        jPanel3 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel31 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtTongThanhTien = new javax.swing.JTextField();
        jPanel22 = new javax.swing.JPanel();
        btnXoaDong = new javax.swing.JButton();
        btnXoaRong = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnTaoPhieu = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtMaPhieuTraHang = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jPanel18 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jPanel19 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtMaHoaDonTrongPhieuTraHang = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTraHang = new javax.swing.JTable();

        setLayout(new java.awt.GridLayout(1, 0));

        jPanel8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel8KeyPressed(evt);
            }
        });
        jPanel8.setLayout(new java.awt.BorderLayout());

        jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.Y_AXIS));

        jPanel13.setLayout(new java.awt.GridLayout(1, 2));
        jPanel13.add(jPanel26);

        jPanel9.add(jPanel13);

        jPanel11.setLayout(new java.awt.GridLayout(1, 2));

        jPanel14.setLayout(new javax.swing.BoxLayout(jPanel14, javax.swing.BoxLayout.LINE_AXIS));

        jPanel25.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        jPanel25.add(jPanel27);

        txtNhapMaHoaDon.setText("Nhập mã hóa đơn [F3]");
        txtNhapMaHoaDon.setPreferredSize(new java.awt.Dimension(400, 22));
        txtNhapMaHoaDon.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNhapMaHoaDonFocusGained(evt);
            }
        });
        txtNhapMaHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNhapMaHoaDonActionPerformed(evt);
            }
        });
        txtNhapMaHoaDon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNhapMaHoaDonKeyPressed(evt);
            }
        });
        jPanel25.add(txtNhapMaHoaDon);

        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });
        jPanel25.add(btnTimKiem);

        jPanel14.add(jPanel25);

        jPanel11.add(jPanel14);

        jPanel30.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnChonTatCa.setText("Chọn tất cả [F7]");
        btnChonTatCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonTatCaActionPerformed(evt);
            }
        });
        jPanel30.add(btnChonTatCa);

        btnBoChonTatCa.setText("Bỏ chọn tất cả [F8]");
        btnBoChonTatCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBoChonTatCaActionPerformed(evt);
            }
        });
        jPanel30.add(btnBoChonTatCa);

        jPanel23.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));
        jPanel23.add(jPanel12);

        jLabel6.setText("Số lượng đã chọn: 0");
        jPanel23.add(jLabel6);

        jPanel30.add(jPanel23);

        btnXacNhan.setText("Xác nhận [F4]");
        btnXacNhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXacNhanMouseClicked(evt);
            }
        });
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });
        jPanel30.add(btnXacNhan);
        jPanel30.add(jPanel16);

        jPanel11.add(jPanel30);

        jPanel9.add(jPanel11);

        jPanel8.add(jPanel9, java.awt.BorderLayout.PAGE_START);

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Chi tiết hóa đơn"));
        jPanel10.setLayout(new javax.swing.BoxLayout(jPanel10, javax.swing.BoxLayout.Y_AXIS));

        jScrollPane2.setBorder(null);

        tblCTHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã CTHD", "Tên sản phẩm", "Số lượng", "Đơn vị tính", "Đơn giá", "Giảm giá", "Thành tiền", "Chọn"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCTHD.setShowGrid(false);
        tblCTHD.setShowHorizontalLines(true);
        tblCTHD.setShowVerticalLines(true);
        jScrollPane2.setViewportView(tblCTHD);
        if (tblCTHD.getColumnModel().getColumnCount() > 0) {
            tblCTHD.getColumnModel().getColumn(0).setMinWidth(50);
            tblCTHD.getColumnModel().getColumn(0).setMaxWidth(50);
            tblCTHD.getColumnModel().getColumn(1).setMinWidth(0);
            tblCTHD.getColumnModel().getColumn(1).setMaxWidth(0);
            tblCTHD.getColumnModel().getColumn(2).setMinWidth(300);
            tblCTHD.getColumnModel().getColumn(2).setMaxWidth(300);
            tblCTHD.getColumnModel().getColumn(8).setResizable(false);
        }

        jPanel10.add(jScrollPane2);
        jScrollPane2.getAccessibleContext().setAccessibleName("");

        jPanel8.add(jPanel10, java.awt.BorderLayout.CENTER);

        jToolBar1.setRollover(true);
        jPanel8.add(jToolBar1, java.awt.BorderLayout.PAGE_END);

        jTabbedPane1.addTab("Tìm hóa đơn", jPanel8);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel20.setMinimumSize(new java.awt.Dimension(474, 33));
        jPanel20.setLayout(new javax.swing.BoxLayout(jPanel20, javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jPanel31.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jLabel5.setText("Tổng tiền hoàn trả");
        jPanel31.add(jLabel5);

        txtTongThanhTien.setEditable(false);
        txtTongThanhTien.setPreferredSize(new java.awt.Dimension(160, 22));
        jPanel31.add(txtTongThanhTien);

        jPanel1.add(jPanel31);
        jPanel1.add(jPanel22);

        btnXoaDong.setText("Xóa dòng [F9]");
        btnXoaDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaDongActionPerformed(evt);
            }
        });
        jPanel1.add(btnXoaDong);

        btnXoaRong.setText("Xóa rỗng [F10]");
        btnXoaRong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaRongActionPerformed(evt);
            }
        });
        jPanel1.add(btnXoaRong);
        jPanel1.add(jPanel2);

        btnTaoPhieu.setText("Tạo phiếu [F6]");
        btnTaoPhieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoPhieuActionPerformed(evt);
            }
        });
        jPanel1.add(btnTaoPhieu);
        jPanel1.add(jPanel17);

        jPanel20.add(jPanel1);

        jPanel3.add(jPanel20, java.awt.BorderLayout.PAGE_END);

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.Y_AXIS));

        jPanel6.setLayout(new java.awt.GridLayout(2, 2));

        jLabel1.setText("Mã phiếu trả hàng");
        jLabel1.setPreferredSize(new java.awt.Dimension(110, 16));
        jPanel7.add(jLabel1);

        txtMaPhieuTraHang.setEditable(false);
        txtMaPhieuTraHang.setPreferredSize(new java.awt.Dimension(250, 22));
        jPanel7.add(txtMaPhieuTraHang);

        jPanel6.add(jPanel7);

        jLabel2.setText("Nhân viên");
        jLabel2.setPreferredSize(new java.awt.Dimension(80, 16));
        jPanel15.add(jLabel2);

        jTextField3.setEditable(false);
        jTextField3.setPreferredSize(new java.awt.Dimension(250, 22));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel15.add(jTextField3);

        jPanel6.add(jPanel15);

        jLabel3.setText("Ngày lập phiếu");
        jLabel3.setPreferredSize(new java.awt.Dimension(110, 16));
        jPanel18.add(jLabel3);

        jTextField5.setEditable(false);
        jTextField5.setPreferredSize(new java.awt.Dimension(250, 22));
        jPanel18.add(jTextField5);

        jPanel6.add(jPanel18);

        jLabel4.setText("Mã hóa đơn");
        jLabel4.setPreferredSize(new java.awt.Dimension(80, 16));
        jPanel19.add(jLabel4);

        txtMaHoaDonTrongPhieuTraHang.setEditable(false);
        txtMaHoaDonTrongPhieuTraHang.setPreferredSize(new java.awt.Dimension(250, 22));
        txtMaHoaDonTrongPhieuTraHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaHoaDonTrongPhieuTraHangActionPerformed(evt);
            }
        });
        jPanel19.add(txtMaHoaDonTrongPhieuTraHang);

        jPanel6.add(jPanel19);

        jPanel4.add(jPanel6);

        jPanel3.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.Y_AXIS));

        jPanel21.setBorder(javax.swing.BorderFactory.createTitledBorder("Chi tiết phiếu trả hàng"));
        jPanel21.setLayout(new javax.swing.BoxLayout(jPanel21, javax.swing.BoxLayout.Y_AXIS));

        tblTraHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Tên sản phẩm", "Số lượng", "Đơn giá", "Giảm giá", "Thành tiền", "Lý do trả", "Sản phẩm nguyên vẹn", "Giá trị hoàn trả", "Thành tiền hoàn trả", "Mã CTHD"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false, false, true, true, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTraHang.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tblTraHangPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(tblTraHang);
        if (tblTraHang.getColumnModel().getColumnCount() > 0) {
            tblTraHang.getColumnModel().getColumn(0).setMinWidth(50);
            tblTraHang.getColumnModel().getColumn(0).setMaxWidth(50);
            tblTraHang.getColumnModel().getColumn(1).setMinWidth(200);
            tblTraHang.getColumnModel().getColumn(1).setMaxWidth(200);
            tblTraHang.getColumnModel().getColumn(6).setMinWidth(200);
            tblTraHang.getColumnModel().getColumn(7).setMinWidth(100);
            tblTraHang.getColumnModel().getColumn(10).setMinWidth(0);
            tblTraHang.getColumnModel().getColumn(10).setMaxWidth(0);
        }

        jPanel21.add(jScrollPane1);

        jPanel5.add(jPanel21);

        jPanel3.add(jPanel5, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Phiếu trả hàng", jPanel3);

        add(jTabbedPane1);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNhapMaHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNhapMaHoaDonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNhapMaHoaDonActionPerformed

    private void btnXoaDongActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnXoaDongActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) tblTraHang.getModel();
        dtm.removeRow(tblTraHang.getSelectedRow());
    }// GEN-LAST:event_btnXoaDongActionPerformed

    private void txtMaHoaDonTrongPhieuTraHangActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtMaHoaDonTrongPhieuTraHangActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtMaHoaDonTrongPhieuTraHangActionPerformed

    private void jXDatePicker1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jXDatePicker1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jXDatePicker1ActionPerformed

    private void txtNhapMaHoaDonFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_txtNhapMaHoaDonFocusGained
        // TODO add your handling code here:
        txtNhapMaHoaDon.setText("HD-181225-0080");
    }// GEN-LAST:event_txtNhapMaHoaDonFocusGained

    private void txtNhapMaHoaDonKeyPressed(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_txtNhapMaHoaDonKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String maHoaDon = txtNhapMaHoaDon.getText();
            addHoaDon(maHoaDon);
        }
    }// GEN-LAST:event_txtNhapMaHoaDonKeyPressed

    private void btnXacNhanMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnXacNhanMouseClicked
        // TODO add your handling code here:

    }// GEN-LAST:event_btnXacNhanMouseClicked

    private void btnXoaRongActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnXoaRongActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) tblTraHang.getModel();
        dtm.setRowCount(0);
        txtTongThanhTien.setText("");
    }// GEN-LAST:event_btnXoaRongActionPerformed

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnXacNhanActionPerformed
        // TODO add your handling code here:
        try {
            jTextField3.setText(NhanVienDAO.getNhanVienTheoMaNV(GiaoDienChinhGUI.getTk().getTenDangNhap()).getHoTenDem()
                    + " " + NhanVienDAO.getNhanVienTheoMaNV(GiaoDienChinhGUI.getTk().getTenDangNhap()).getTen());
        } catch (Exception e) {

        }
        DefaultTableModel dtmCTHD = (DefaultTableModel) tblCTHD.getModel();

        int soLuongChonHienTai = 0;
        for (int i = 0; i < dtmCTHD.getRowCount(); i++) {
            if (dtmCTHD.getValueAt(i, 8) == Boolean.TRUE && Integer.parseInt(dtmCTHD.getValueAt(i, 3).toString()) > 0) {
                soLuongChonHienTai++;
            }
        }

        jLabel6.setText("Số lượng đã chọn: " + soLuongChonHienTai);

        DefaultTableModel dtmTraHang = (DefaultTableModel) tblTraHang.getModel();
        dtmTraHang.setRowCount(0);

        int count = 0;
        for (int i = 0; i < dtmCTHD.getRowCount(); i++) {
            System.out.println(1);
            if (dtmCTHD.getValueAt(i, 8) == Boolean.TRUE && Integer.parseInt(dtmCTHD.getValueAt(i, 3).toString()) > 0) {
                if (HoaDonDAO.getSoPTH(txtNhapMaHoaDon.getText()) > 0) {
                    themDongBangPhieuTraHangDaTungTraRoi(dtmCTHD.getValueAt(i, 1).toString());
                    count++;
                } else if (HoaDonDAO.getSoPTH(txtNhapMaHoaDon.getText()) == 0) {
                    themDongBangPhieuTraHang(dtmCTHD.getValueAt(i, 1).toString());
                    count++;
                }
            }
        }
        capNhatTongTienTra();
        if (count > 0) {
            jTabbedPane1.setSelectedIndex(1);
        } else {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn sản phẩm muốn trả");
        }

    }// GEN-LAST:event_btnXacNhanActionPerformed

    private void btnBoChonTatCaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBoChonTatCaActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtmTraHang = (DefaultTableModel) tblTraHang.getModel();
        dtmTraHang.setRowCount(0);

        DefaultTableModel dtmCTHD = (DefaultTableModel) tblCTHD.getModel();
        for (int i = 0; i < dtmCTHD.getRowCount(); i++) {
            if (dtmCTHD.getValueAt(i, 8) == Boolean.TRUE) {
                dtmCTHD.setValueAt(Boolean.FALSE, i, 8);
            }
        }
    }// GEN-LAST:event_btnBoChonTatCaActionPerformed

    private void btnTaoPhieuActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnTaoPhieuActionPerformed
        // TODO add your handling code here:
        int chon = JOptionPane.showConfirmDialog(null, "Xác nhận tạo phiếu trả?", "Xác nhận",
                JOptionPane.YES_NO_OPTION);
        if (chon == JOptionPane.YES_OPTION) {

            PhieuTraHang pth = getPhieuTraHang();

            List<ChiTietPhieuTraHang> list = getListCTPTH(pth);
            //
            luuPhieuVaoCSDL(pth, list);
            taoPhieuTraHang(pth, list);
            //
            jTabbedPane1.setSelectedIndex(0);
            xoaRongTatCa();
        } else {

        }

    }// GEN-LAST:event_btnTaoPhieuActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnTimKiemActionPerformed
        String maHoaDon = txtNhapMaHoaDon.getText();
        // Reset thông tin khi tìm kiếm mới
        resetInfoPanels();

        if (maHoaDon != null && !maHoaDon.trim().isEmpty()) {
            // Kiểm tra hóa đơn có tồn tại không
            HoaDon hoaDon = HoaDonDAO.getHoaDonTheoMaHD(maHoaDon);

            if (hoaDon == null) {
                JOptionPane.showMessageDialog(null, "Không tìm thấy hóa đơn với mã: " + maHoaDon);
                return;
            }

            // Kiểm tra hóa đơn có quá 30 ngày không
            long ngayLap = ChronoUnit.DAYS.between(LocalDate.now(), hoaDon.getNgayLapHoaDon()) * -1;
            if (ngayLap > 30) {
                JOptionPane.showMessageDialog(null, "Hóa đơn đã lập hơn 30 ngày, theo nguyên tắc không thể trả hàng!");
                return;
            }

            // Hóa đơn hợp lệ, thêm dữ liệu và cập nhật 3 ô thông tin
            addHoaDon(maHoaDon);
        }
    }// GEN-LAST:event_btnTimKiemActionPerformed

    private void btnChonTatCaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnChonTatCaActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtmCTHD = (DefaultTableModel) tblCTHD.getModel();

        for (int i = 0; i < dtmCTHD.getRowCount(); i++) {
            dtmCTHD.setValueAt(Boolean.TRUE, i, 8);
        }
    }// GEN-LAST:event_btnChonTatCaActionPerformed

    private void tblTraHangPropertyChange(java.beans.PropertyChangeEvent evt) {// GEN-FIRST:event_tblTraHangPropertyChange
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) tblTraHang.getModel();
        int selectRow = tblTraHang.getSelectedRow();
        if (selectRow >= 0) {
            int soLuong = Integer.parseInt(dtm.getValueAt(selectRow, 2).toString());
            String maCTHD = dtm.getValueAt(selectRow, 10).toString();
            if (soLuong <= ChiTietHoaDonDAO.getChiTietHoaDonTheoMaCTHD(maCTHD).getSoLuong() && soLuong > 0) {
                double donGia = boDinhDangTien(dtm.getValueAt(selectRow, 3).toString());
                double khuyenMai = boDinhDangTien(dtm.getValueAt(selectRow, 4).toString());
                dtm.setValueAt(dinhDangTien(soLuong * donGia - khuyenMai), selectRow, 5);
            } else {
                int stt = selectRow + 1;
                JOptionPane.showMessageDialog(null, "Yêu cầu kiểm tra lại tại STT " + stt + "\n"
                        + "- Số lượng trả bé hơn hoặc bằng số lượng mua\n"
                        + "- Số lượng trả lớn hơn 0 ");
            }

            if (dtm.getValueAt(selectRow, 7) == Boolean.TRUE) {
                dtm.setValueAt("100%", selectRow, 8);
                Object thanhTien = dtm.getValueAt(selectRow, 5);
                dtm.setValueAt(thanhTien, selectRow, 9);
            } else if (dtm.getValueAt(selectRow, 7) == Boolean.FALSE) {
                if (dtm.getValueAt(selectRow, 6)
                        .equals(TruongHopDoiTraEnum.HANG_LOI_DO_NHA_SAN_XUAT.getTruongHopDoiTra())) {
                    dtm.setValueAt("100%", selectRow, 8);
                    Object thanhTien = dtm.getValueAt(selectRow, 5);
                    dtm.setValueAt(thanhTien, selectRow, 9);
                } else if (dtm.getValueAt(selectRow, 6)
                        .equals(TruongHopDoiTraEnum.DI_UNG_MAN_CAM.getTruongHopDoiTra())) {
                    dtm.setValueAt("70%", selectRow, 8);
                    String thanhTien = dinhDangTien(boDinhDangTien(dtm.getValueAt(selectRow, 5).toString()) * 0.7);
                    dtm.setValueAt(thanhTien, selectRow, 9);
                } else if (dtm.getValueAt(selectRow, 6)
                        .equals(TruongHopDoiTraEnum.NHU_CAU_KHACH_HANG.getTruongHopDoiTra())) {
                    dtm.setValueAt("Miễn trả hàng", selectRow, 8);
                    dtm.setValueAt(0, selectRow, 9);
                }
            }
            capNhatTongThanhTien();
        }
    }// GEN-LAST:event_tblTraHangPropertyChange

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextField3ActionPerformed

    private void jPanel8KeyPressed(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_jPanel8KeyPressed
        // TODO add your handling code here:
    }// GEN-LAST:event_jPanel8KeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBoChonTatCa;
    private javax.swing.JButton btnChonTatCa;
    private javax.swing.JButton btnTaoPhieu;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JButton btnXoaDong;
    private javax.swing.JButton btnXoaRong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable tblCTHD;
    private javax.swing.JTable tblTraHang;
    private javax.swing.JTextField txtMaHoaDonTrongPhieuTraHang;
    private javax.swing.JTextField txtMaPhieuTraHang;
    private javax.swing.JTextField txtNhapMaHoaDon;
    private javax.swing.JTextField txtTongThanhTien;
    // End of variables declaration//GEN-END:variables

    // Thêm hóa đơn vào "Tìm hóa đơn"
    private void addHoaDon(String maHoaDon) {
        // hóa đơn có pth không?
        boolean coPTH = HoaDonDAO.getSoPTH(maHoaDon) > 0;
        System.out.println(HoaDonDAO.getSoPTH(maHoaDon));
        int tongSoPhieuTraHang = 0;
        //
        List<ChiTietHoaDon> listCTHD;
        HoaDon hoaDon = HoaDonDAO.getHoaDonTheoMaHD(maHoaDon);

        if (coPTH) {
            listCTHD = ChiTietHoaDonDAO.getChiTietHoaDonDaTruPTHTheoMaHD(hoaDon);
            tongSoPhieuTraHang = HoaDonDAO.getSoPTH(maHoaDon);
        } else {
            listCTHD = ChiTietHoaDonDAO.getChiTietHoaDonTheoMaHD(hoaDon);
        }

        long ngayLap = ChronoUnit.DAYS.between(LocalDate.now(), hoaDon.getNgayLapHoaDon()) * -1;
        if (ngayLap <= 30) {
            System.out.println(ngayLap);
            // Them du lieu vao bang cthd
            lblSoLanTra.setText(tongSoPhieuTraHang+"");
            lblSoNgayHD.setText(ngayLap+"");
            lblTongTienTra.setText(dinhDangTien(HoaDonDAO.getTongTienCacPTH(maHoaDon)));
            System.out.println("Sửa thành công");
            themDuLieuCTHDVaoBang(listCTHD);
            taoThongTinPhieu(maHoaDon);
        } else {
            JOptionPane.showMessageDialog(null, "Hóa đơn đã lập hơn 30 ngày, theo nguyên tắc không thể trả hàng!");
        }
    }

    private void themDuLieuCTHDVaoBang(List<ChiTietHoaDon> listCTHD) {
        int stt = 0;
        DefaultTableModel bangCTHD = (DefaultTableModel) tblCTHD.getModel();
        bangCTHD.setRowCount(0);
        Object[] row = new Object[9];
        for (ChiTietHoaDon cthd : listCTHD) {
            stt++;
            String maCTHD = cthd.getMaChiTietHoaDon();
            String tenSanPham = cthd.getDonViTinh().getSanPham().getTen();
            int soLuong = cthd.getSoLuong();
            String donViTinh = cthd.getDonViTinh().getTenDonVi();
            double donGia = cthd.getDonGia();
            double giamGia = cthd.getGiamGia();
            double thanhTien = cthd.getThanhTien() >= 0 ? cthd.getThanhTien() : 0;
            boolean chon = Boolean.FALSE;
            row[0] = stt;
            row[1] = maCTHD;
            row[2] = tenSanPham;
            row[3] = soLuong < 0 ? 0 : soLuong;
            row[4] = donViTinh;
            row[5] = dinhDangTien(donGia);
            row[6] = dinhDangTien(giamGia);
            row[7] = dinhDangTien(thanhTien);
            row[8] = chon;
            if (soLuong <= 0) {
                row[2] = "(Không nhận trả hàng nữa!) " + tenSanPham;
            }
            bangCTHD.addRow(row);
        }
    }

    // Thêm dữ liệu vào "phiếu trả hàng"
    private void themDongBangPhieuTraHang(String maCTHD) {
        ChiTietHoaDon cthd = ChiTietHoaDonDAO.getChiTietHoaDonTheoMaCTHD(maCTHD);
        DefaultTableModel dtm = (DefaultTableModel) tblTraHang.getModel();
        Object[] rowData = new Object[11];

        int stt = dtm.getRowCount() + 1;
        String tenSanPham = cthd.getDonViTinh().getSanPham().getTen();
        int soLuong = cthd.getSoLuong();
        double donGia = cthd.getDonGia();
        double giamGia = cthd.getGiamGia();
        double thanhTien = soLuong * donGia - giamGia;
        String lyDoTra = TruongHopDoiTraEnum.HANG_LOI_DO_NHA_SAN_XUAT.getTruongHopDoiTra();
        boolean sanPhamNguyenVen = Boolean.TRUE;
        String giaTriHoanTra = null;
        double thanhTienHoanTra = 0;

        rowData[0] = stt;
        rowData[1] = tenSanPham;
        rowData[2] = soLuong;
        rowData[3] = dinhDangTien(donGia);
        rowData[4] = dinhDangTien(giamGia);
        rowData[5] = dinhDangTien(thanhTien);
        rowData[6] = lyDoTra;
        rowData[7] = sanPhamNguyenVen;
        rowData[8] = giaTriHoanTra;
        rowData[9] = dinhDangTien(thanhTienHoanTra);
        rowData[10] = maCTHD;

        dtm.addRow(rowData);

        taoLyDo();

    }

    private void themDongBangPhieuTraHangDaTungTraRoi(String maCTHD) {
        ChiTietHoaDon cthd = ChiTietHoaDonDAO.getChiTietHoaDonDaTungTraRoiTheoMaCTHD(maCTHD);
        DefaultTableModel dtm = (DefaultTableModel) tblTraHang.getModel();
        Object[] rowData = new Object[11];

        int stt = dtm.getRowCount() + 1;
        String tenSanPham = cthd.getDonViTinh().getSanPham().getTen();
        int soLuong = cthd.getSoLuong();
        double donGia = cthd.getDonGia();
        double giamGia = cthd.getGiamGia();
        double thanhTien = cthd.getThanhTien();
        String lyDoTra = TruongHopDoiTraEnum.HANG_LOI_DO_NHA_SAN_XUAT.getTruongHopDoiTra();
        boolean sanPhamNguyenVen = Boolean.TRUE;
        String giaTriHoanTra = null;
        double thanhTienHoanTra = 0;

        rowData[0] = stt;
        rowData[1] = tenSanPham;
        rowData[2] = soLuong;
        rowData[3] = dinhDangTien(donGia);
        rowData[4] = dinhDangTien(giamGia);
        rowData[5] = dinhDangTien(thanhTien);
        rowData[6] = lyDoTra;
        rowData[7] = sanPhamNguyenVen;
        rowData[8] = giaTriHoanTra;
        rowData[9] = dinhDangTien(thanhTienHoanTra);
        rowData[10] = maCTHD;
        dtm.addRow(rowData);
        taoLyDo();
    }

    public double boDinhDangTien(String formatted) {
        // Bước 1: Loại bỏ "VNĐ" và khoảng trắng
        String cleaned = formatted.replace("VNĐ", "").trim();

        // Bước 2: Loại bỏ dấu phẩy
        cleaned = cleaned.replace(",", "");

        // Bước 3: Chuyển thành double
        return Double.parseDouble(cleaned);
    }

    private void taoThongTinPhieu(String maHoaDon) {
        txtMaHoaDonTrongPhieuTraHang.setText(maHoaDon);
        int ngay = LocalDate.now().getDayOfMonth();
        int thang = LocalDate.now().getMonthValue();
        int nam = LocalDate.now().getYear();
        jTextField5.setText(ngay + "/" + thang + "/" + nam);

        String maPhieuTraHang = phatSinhMaPhieuTraHang();
        txtMaPhieuTraHang.setText(maPhieuTraHang);
    }

    private void taoLyDo() {
        JComboBox<String> cbbLyDo = new JComboBox<>();
        cbbLyDo.addItem(TruongHopDoiTraEnum.HANG_LOI_DO_NHA_SAN_XUAT.getTruongHopDoiTra());
        cbbLyDo.addItem(TruongHopDoiTraEnum.DI_UNG_MAN_CAM.getTruongHopDoiTra());
        cbbLyDo.addItem(TruongHopDoiTraEnum.NHU_CAU_KHACH_HANG.getTruongHopDoiTra());

        TableColumn colLyDo = tblTraHang.getColumnModel().getColumn(6);
        colLyDo.setCellEditor(new DefaultCellEditor(cbbLyDo));
    }

    private void capNhatTongThanhTien() {
        DefaultTableModel dtm = (DefaultTableModel) tblTraHang.getModel();
        double tongThanhTien = 0;
        for (int i = 0; i < dtm.getRowCount(); i++) {
            tongThanhTien = tongThanhTien + boDinhDangTien(dtm.getValueAt(i, 9).toString());
        }
        txtTongThanhTien.setText(dinhDangTien(tongThanhTien));
    }

    private String phatSinhMaPhieuTraHang() {
        int ngay = LocalDate.now().getDayOfMonth();
        int thang = LocalDate.now().getMonthValue();
        int nam = LocalDate.now().getYear();
        nam = nam % 1000;
        String ngayThangNam = String.format("%02d%02d%02d", ngay, thang, nam);
        int soPhieuHomNay = PhieuTraHangDAO.phieuTraHangMoiNhatHomNay();
        String maPhieuTraHang = String.format("PTH-%s-%04d", ngayThangNam, soPhieuHomNay + 1);

        return maPhieuTraHang;
    }

    private List<ChiTietPhieuTraHang> getListCTPTH(PhieuTraHang pth) {

        DefaultTableModel dtm = (DefaultTableModel) tblTraHang.getModel();
        List<ChiTietPhieuTraHang> listPTH = new ArrayList<>();

        if (dtm.getColumnCount() == 0) {
            throw new IllegalArgumentException("Không có CTPTH");
        } else {
            for (int i = 0; i < dtm.getRowCount(); i++) {

                String maCTHD = dtm.getValueAt(i, 10).toString();

                ChiTietHoaDon cthd = ChiTietHoaDonDAO.getChiTietHoaDonTheoMaCTHD(maCTHD);
                TruongHopDoiTraEnum truongHopDoiTra = TruongHopDoiTraEnum.HANG_LOI_DO_NHA_SAN_XUAT;
                if (dtm.getValueAt(i, 6).toString()
                        .equals(TruongHopDoiTraEnum.HANG_LOI_DO_NHA_SAN_XUAT.getTruongHopDoiTra())) {
                    truongHopDoiTra = TruongHopDoiTraEnum.HANG_LOI_DO_NHA_SAN_XUAT;
                } else if (dtm.getValueAt(i, 6).toString()
                        .equals(TruongHopDoiTraEnum.DI_UNG_MAN_CAM.getTruongHopDoiTra())) {
                    truongHopDoiTra = TruongHopDoiTraEnum.DI_UNG_MAN_CAM;
                } else if (dtm.getValueAt(i, 6).toString()
                        .equals(TruongHopDoiTraEnum.NHU_CAU_KHACH_HANG.getTruongHopDoiTra())) {
                    truongHopDoiTra = TruongHopDoiTraEnum.NHU_CAU_KHACH_HANG;
                }
                TinhTrangSanPhamEnum tinhTrang = TinhTrangSanPhamEnum.HANG_NGUYEN_VEN;
                if (dtm.getValueAt(i, 7) == Boolean.FALSE) {
                    tinhTrang = TinhTrangSanPhamEnum.HANG_KHONG_NGUYEN_VEN;
                }

                int soLuong = Integer.parseInt(dtm.getValueAt(i, 2).toString());
                String giaTriHoanTra = dtm.getValueAt(i, 8).toString();

                double thanhTienHoanTra = boDinhDangTien(dtm.getValueAt(i, 9).toString());

                ChiTietPhieuTraHang ctpth = new ChiTietPhieuTraHang();
                ctpth.setChiTietHoaDon(cthd);
                ctpth.setPhieuTraHang(pth);
                ctpth.setTruongHopDoiTra(truongHopDoiTra);
                ctpth.setTinhTrangSanPham(tinhTrang);
                ctpth.setTinhTrangSanPham(tinhTrang);
                ctpth.setSoLuong(soLuong);
                ctpth.setThanhTienHoanTra(thanhTienHoanTra);
                ctpth.setGiaTriHoanTra(giaTriHoanTra);
                listPTH.add(ctpth);
            }
        }
        return listPTH;
    }

    private PhieuTraHang getPhieuTraHang() {
        PhieuTraHang pth = new PhieuTraHang();
        String maPTH = txtMaPhieuTraHang.getText();
        String maNV = null;
        try {
            maNV = NhanVienDAO.getNhanVienTheoMaNV(GiaoDienChinhGUI.getTk().getTenDangNhap()).getMaNV();
        } catch (Exception e) {

        }

        String maHD = txtMaHoaDonTrongPhieuTraHang.getText();
        LocalDateTime ngayLap = LocalDateTime.now();
        double tongTienHoanTra = boDinhDangTien(txtTongThanhTien.getText());

        NhanVien nv = NhanVienDAO.timNVTheoMa(maNV);
        HoaDon hd = HoaDonDAO.getHoaDonTheoMaHD(maHD);

        pth.setMaPhieuTraHang(maPTH);
        pth.setNhanVien(nv);
        pth.setHoaDon(hd);
        pth.setNgayLapPhieuTraHang(ngayLap);
        pth.setTongTienHoanTra(tongTienHoanTra);

        return pth;

    }

    private void taoPhieuTraHang(PhieuTraHang pth, List<ChiTietPhieuTraHang> list) {
        StringBuilder sb = new StringBuilder();
        // init header
        sb.append("====================================================================\n");
        sb.append("                         Phiếu Trả Hàng\n");
        sb.append("====================================================================\n");
        // init thong tin co ban
        sb.append(String.format("Mã phiếu trả hàng  : %s \n", pth.getMaPhieuTraHang()));
        sb.append(String.format("Tên nhân viên      : %s \n", pth.getNhanVien().getTen()));
        sb.append(String.format("Mã hóa đơn         : %s \n", pth.getHoaDon().getMaHoaDon()));
        sb.append(String.format("Ngày lập phiếu     : %s \n", pth.getNgayLapPhieuTraHang()));
        sb.append("--------------------------------------------------------------------\n");
        // init chi tiet tra hang
        sb.append(String.format("%-4s %-50s %-4s %-15s %-10s %-15s %-15s %-15s %-35s %-20s %-15s \n",
                "STT", "Tên sản phẩm", "SL", "Đơn giá", "ĐVT",
                "Giảm giá", "Thành tiền", "Tình trạng SP", "Lý do trả",
                "Phần trăm hoàn trả", "Thành tiền trả"));
        sb.append("--------------------------------------------------------------------\n");

        for (int i = 0; i < list.size(); i++) {
            String thanhTien = dinhDangTien(list.get(i).getSoLuong() * list.get(i).getChiTietHoaDon().getDonGia()
                    - list.get(i).getChiTietHoaDon().getGiamGia());
            String donGia = dinhDangTien(list.get(i).getChiTietHoaDon().getDonGia());
            String giamGia = dinhDangTien(list.get(i).getChiTietHoaDon().getGiamGia());
            String tinhTrangSP = (list.get(i).getTinhTrangSanPham() == TinhTrangSanPhamEnum.HANG_NGUYEN_VEN)
                    ? "Nguyên vẹn"
                    : "Đã sử dụng";
            String phanTramHoanTra = list.get(i).getGiaTriHoanTra();
            String thanhTienTra = dinhDangTien(list.get(i).getThanhTienHoanTra());
            String donViTinh = list.get(i).getChiTietHoaDon().getDonViTinh().getTenDonVi();

            sb.append(String.format("%-4d %-50s %-4d %-15s %-10s %-15s %-15s %-15s %-35s %-20s %-15s \n",
                    i + 1, list.get(i).getChiTietHoaDon().getDonViTinh().getSanPham().getTen(),
                    list.get(i).getSoLuong(), donGia, donViTinh,
                    giamGia, thanhTien, tinhTrangSP, list.get(i).getTruongHopDoiTra().getTruongHopDoiTra(),
                    phanTramHoanTra, thanhTienTra));
            sb.append("--------------------------------------------------------------------\n");
        }

        // init footer
        sb.append(String.format("Tổng tiền hoàn trả : %s \n", dinhDangTien(pth.getTongTienHoanTra())));
        sb.append("====================================================================\n");
        sb.append("         CẢM ƠN QUÝ KHÁCH, HẸN GẶP LẠI!\n");
        sb.append("====================================================================\n");

        JTextArea textArea = new JTextArea(sb.toString());
        textArea.setEditable(false);
        textArea.setFont(new Font("Monospaced", Font.PLAIN, 13));
        JScrollPane scroll = new JScrollPane(textArea);
        scroll.setPreferredSize(new Dimension(600, 500));
        JOptionPane.showMessageDialog(null, scroll, "Phiếu trả hàng" + pth.getMaPhieuTraHang(),
                JOptionPane.INFORMATION_MESSAGE);
    }

    private void luuPhieuVaoCSDL(PhieuTraHang pth, List<ChiTietPhieuTraHang> list) {
        PhieuTraHangDAO.themPhieuTra(pth);
        for (ChiTietPhieuTraHang ctpth : list) {
            ChiTietPhieuTraDAO.insertChiTietPhieuTra(ctpth);
        }
    }

    private void capNhatTongTienTra() {
        // cập nhật lại thành tiền khi đổi số lượng
        DefaultTableModel dtm = (DefaultTableModel) tblTraHang.getModel();
        for (int i = 0; i < tblTraHang.getRowCount(); i++) {
            int soLuong = Integer.parseInt(dtm.getValueAt(i, 2).toString());
            String maCTHD = dtm.getValueAt(i, 10).toString();
            if (soLuong <= ChiTietHoaDonDAO.getChiTietHoaDonDaTungTraRoiTheoMaCTHD(maCTHD).getSoLuong()) {
                double donGia = boDinhDangTien(dtm.getValueAt(i, 3).toString());
                double khuyenMai = boDinhDangTien(dtm.getValueAt(i, 4).toString());
                dtm.setValueAt(dinhDangTien(soLuong * (donGia - khuyenMai)), i, 5);
            } else {
                int stt = i + 1;
                JOptionPane.showMessageDialog(null,
                        "Yêu cầu số lượng trả bé hơn hoặc bằng số lượng mua, số lượng trả lớn hơn 0 tại STT: " + stt);
            }
        }

        for (int i = 0; i < dtm.getRowCount(); i++) {
            if (dtm.getValueAt(i, 7) == Boolean.TRUE) {
                dtm.setValueAt("100%", i, 8);
                Object thanhTien = dtm.getValueAt(i, 5);
                dtm.setValueAt(thanhTien, i, 9);
            } else if (dtm.getValueAt(i, 7) == Boolean.FALSE) {
                if (dtm.getValueAt(i, 6).equals(TruongHopDoiTraEnum.HANG_LOI_DO_NHA_SAN_XUAT.getTruongHopDoiTra())) {
                    dtm.setValueAt("100%", i, 8);
                    Object thanhTien = dtm.getValueAt(i, 5);
                    dtm.setValueAt(thanhTien, i, 9);
                } else if (dtm.getValueAt(i, 6).equals(TruongHopDoiTraEnum.DI_UNG_MAN_CAM.getTruongHopDoiTra())) {
                    dtm.setValueAt("70%", i, 8);
                    String thanhTien = dinhDangTien(boDinhDangTien(dtm.getValueAt(i, 5).toString()) * 0.7);
                    dtm.setValueAt(thanhTien, i, 9);
                } else if (dtm.getValueAt(i, 6).equals(TruongHopDoiTraEnum.NHU_CAU_KHACH_HANG.getTruongHopDoiTra())) {
                    dtm.setValueAt("Miễn trả hàng", i, 8);
                    dtm.setValueAt(0, i, 9);
                }
            }
        }
        capNhatTongThanhTien();
    }

    // CRUD, hiệu chỉnh
    private String dinhDangTien(double thanhTien) {
        DecimalFormat formatter = new DecimalFormat("#,###");
        return formatter.format(thanhTien) + " VNĐ";
    }

    private void xoaRongTatCa() {
        DefaultTableModel dtmCTHD = (DefaultTableModel) tblCTHD.getModel();
        dtmCTHD.setRowCount(0);
        txtNhapMaHoaDon.setText("Nhập mã hóa đơn");
        jLabel6.setText("Số lượng đã chọn: 0");

        DefaultTableModel dtmTraHang = (DefaultTableModel) tblTraHang.getModel();
        dtmTraHang.setRowCount(0);
        txtMaPhieuTraHang.setText("");
        jTextField3.setText("");
        jTextField5.setText("");
        txtMaHoaDonTrongPhieuTraHang.setText("");
        txtTongThanhTien.setText("");

    }

    private void mapKeyToFocus(String key, JComponent component) {
        InputMap im = component.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        ActionMap am = component.getActionMap();

        im.put(KeyStroke.getKeyStroke(key), "focus_" + key);
        am.put("focus_" + key, new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                component.requestFocus();
                if (component instanceof JTextField jTextField) {
                    jTextField.selectAll();
                }
            }
        });
    }

    private void mapKeyToClickButton(String key, AbstractButton button) {
        InputMap im = button.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        ActionMap am = button.getActionMap();

        im.put(KeyStroke.getKeyStroke(key), "click_" + key);
        am.put("click_" + key, new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                button.doClick(); // kích hoạt sự kiện button
            }
        });
    }

    /**
     * Reset 3 ô thông tin về giá trị mặc định
     */
    private void resetInfoPanels() {
        lblSoLanTra.setText("0");
        lblSoNgayHD.setText("0");
        lblTongTienTra.setText("0 VND");
    }

    /**
     * Cập nhật 3 ô thông tin khi tìm kiếm thành công
     */
    /**
     * Khởi tạo 3 JLabel cho info panels
     */
    private void initInfoPanels() {
        lblSoLanTra = new javax.swing.JLabel("0");
        lblSoNgayHD = new javax.swing.JLabel("0");
        lblTongTienTra = new javax.swing.JLabel("0 VND");

        // Tạo panel chứa 3 ô info
        javax.swing.JPanel pnlInfos = new javax.swing.JPanel(new java.awt.GridLayout(1, 3, 10, 0));
        pnlInfos.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        // Ô 1: Tổng số lần đã trả
        javax.swing.JPanel pnlSoLanTra = createInfoCard("Tổng số phiếu trả của hóa đơn", lblSoLanTra,
                new java.awt.Color(232, 245, 233), new java.awt.Color(46, 125, 50));
        pnlInfos.add(pnlSoLanTra);

        // Ô 2: Số ngày kể từ khi lập hóa đơn
        javax.swing.JPanel pnlSoNgayHD = createInfoCard("Số ngày kể từ khi lập hóa đơn", lblSoNgayHD,
                new java.awt.Color(255, 243, 224), new java.awt.Color(230, 126, 34));
        pnlInfos.add(pnlSoNgayHD);

        // Ô 3: Tổng tiền đã trả
        javax.swing.JPanel pnlTongTienTra = createInfoCard("Tổng số tiền đã trả", lblTongTienTra,
                new java.awt.Color(255, 235, 238), new java.awt.Color(198, 40, 40));
        pnlInfos.add(pnlTongTienTra);

        // Thêm vào jPanel9 (sau khu vực tìm kiếm, trước bảng chi tiết)
        if (jPanel9 != null) {
            jPanel9.add(pnlInfos);
            jPanel9.revalidate();
            jPanel9.repaint();
        }
    }

    /**
     * Tạo một card thông tin với tiêu đề + giá trị
     */
    private javax.swing.JPanel createInfoCard(String title, javax.swing.JLabel valueLabel,
            java.awt.Color bgColor, java.awt.Color titleColor) {
        javax.swing.JPanel card = new javax.swing.JPanel(new java.awt.BorderLayout());
        card.setBackground(bgColor);
        card.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                javax.swing.BorderFactory.createLineBorder(titleColor, 2, true),
                javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10)));

        // Tiêu đề
        javax.swing.JLabel lblTitle = new javax.swing.JLabel(title);
        lblTitle.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
        lblTitle.setForeground(titleColor);
        card.add(lblTitle, java.awt.BorderLayout.NORTH);

        // Giá trị
        valueLabel.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 28));
        valueLabel.setForeground(titleColor);
        valueLabel.setHorizontalAlignment(javax.swing.JLabel.CENTER);
        card.add(valueLabel, java.awt.BorderLayout.CENTER);

        return card;
    }

//    private void capNhatThongTinHoaDon(String maHoaDon) {
//        try {
//            // 1. Số lần đã trả
//            int soLanTra = demSoLanTraHang(maHoaDon);
//            System.out.println("DEBUG: soLanTra = " + soLanTra);
//            lblSoLanTra.setText(String.valueOf(soLanTra));
//
//            // 2. Số ngày kể từ khi lập hóa đơn
//            HoaDon hoaDon = HoaDonDAO.getHoaDonTheoMaHD(maHoaDon);
//            if (hoaDon == null) {
//                resetInfoPanels();
//                return;
//            }
//            long soNgay = ChronoUnit.DAYS.between(hoaDon.getNgayLapHoaDon(), LocalDate.now());
//            System.out.println("DEBUG: soNgay = " + soNgay);
//            lblSoNgayHD.setText(String.valueOf(soNgay));
//
//            // 3. Tổng tiền đã trả
//            double tongTienTra = tinhTongTienTraHang(maHoaDon);
//            System.out.println("DEBUG: tongTienTra = " + tongTienTra);
//            lblTongTienTra.setText(dinhDangTien(tongTienTra) + " VND");
//        } catch (Exception e) {
//            e.printStackTrace();
//            resetInfoPanels();
//        }
//    }

    /**
     * Đếm số lượng phiếu trả hàng của một hóa đơn
     */
    private int demSoLanTraHang(String maHoaDon) {
        try {
            List<PhieuTraHang> dsPhieuTra = PhieuTraHangDAO.timPTHTheoMaHD(maHoaDon);
            return dsPhieuTra != null ? dsPhieuTra.size() : 0;
        } catch (Exception e) {
            return 0;
        }
    }

    /**
     * Tính tổng tiền đã trả hàng của một hóa đơn
     */
    private double tinhTongTienTraHang(String maHoaDon) {
        try {
            List<PhieuTraHang> dsPhieuTra = PhieuTraHangDAO.timPTHTheoMaHD(maHoaDon);
            double tongTien = 0;

            if (dsPhieuTra != null) {
                for (PhieuTraHang pth : dsPhieuTra) {
                    List<ChiTietPhieuTraHang> dsChiTiet = PhieuTraHangDAO.getChiTietTheoMaPTH(pth);
                    if (dsChiTiet != null) {
                        for (ChiTietPhieuTraHang ctpth : dsChiTiet) {
                            tongTien += ctpth.getThanhTienHoanTra();
                        }
                    }
                }
            }
            return tongTien;
        } catch (Exception e) {
            return 0;
        }
    }

}
